export const NOTIFICATION_REGISTRY_VERSION = "2026-08-24";

export const DELIVERY = {
  PUSH: "push",
  BELL: "bell",
  ADMIN_INBOX: "admin_inbox",
  EMAIL: "email",
};

export const DEPRECATED_NOTIFICATION_TYPES = {
  fallback_listing: "Deprecated legacy fallback payment/listing type. Map to neighborhood_sale_fallback_applied when needed.",
  vendor: "Deprecated generic vendor bucket. Use vendor_account, vendor_event, vendor_checkin, or vendor_subscription.",
  nearby_listing: "Deprecated per-listing nearby alert. Replaced by nearby_listings_daily_digest.",
  vendor_near_me: "Legacy vendor check-in push type. New records should use vendor_checkin.",
};

export const NOTIFICATION_REGISTRY = {
  nearby_listings_daily_digest: {
    recipient: "users with Listings Near Me enabled",
    trigger: "Daily 5:00 AM summary of listings opening today within the user's radius",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Yard sales near you today",
    message: "Summarized count of nearby listings happening today.",
    deep_link: "/",
  },
  listing_open: {
    recipient: "listing owner",
    trigger: "User-selected open time, not the status becoming active",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Your listing is open",
    message: "Your Yardit listing is scheduled to be open now.",
    deep_link: "/MyListings",
  },
  saved_listing_active: {
    recipient: "user who saved or tracked the listing",
    trigger: "A saved listing reaches its open time",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "future",
    title: "Saved listing is active",
    message: "A listing you saved is open now.",
    deep_link: "/ListingDetail",
  },
  listing_status_change: {
    recipient: "listing owner",
    trigger: "Admin changes a listing status",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Listing Status Changed",
    message: "Listing status changed.",
    deep_link: "/MyListings",
  },
  listing_removed: {
    recipient: "listing owner",
    trigger: "Admin hides, removes, or suspends a listing",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Listing Removed",
    message: "Listing was removed or suspended.",
    deep_link: "/MyListings",
  },
  listing_flagged: {
    recipient: "listing owner",
    trigger: "Listing is placed under review",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Listing Flagged",
    message: "Listing is under review.",
    deep_link: "/MyListings",
  },
  listing_expired: {
    recipient: "listing owner",
    trigger: "Listing reaches its end time",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Listing Expired",
    message: "Listing expired.",
    deep_link: "/MyListings",
  },
  join_request: {
    recipient: "Neighborhood Sale organizer",
    trigger: "A seller requests to join a Neighborhood Sale",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Join request received",
    message: "A seller requested to join your Neighborhood Sale.",
    deep_link: "/MyListings",
  },
  join_request_accepted: {
    recipient: "requesting seller",
    trigger: "Organizer approves a join request",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale Request",
    message: "Your request was approved.",
    deep_link: "/ListingDetail",
  },
  join_request_denied: {
    recipient: "requesting seller",
    trigger: "Organizer denies a join request",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale Request",
    message: "Your request was denied.",
    deep_link: "/ListingDetail",
  },
  join_request_resolved: {
    recipient: "Neighborhood Sale organizer",
    trigger: "Organizer completes approval/denial action on an incoming join request",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Join request resolved",
    message: "You responded to a join request.",
    deep_link: "/MyListings",
  },
  co_host_invite: {
    recipient: "requested co-host",
    trigger: "Organizer asks a verified address holder to co-host a Neighborhood Sale",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale Co-Host Request",
    message: "An organizer requested your address for a Neighborhood Sale.",
    deep_link: "/Notifications",
  },
  residential_access_request: {
    recipient: "yard sale owner",
    trigger: "Another household member requests access to an existing residential yard sale",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Household access request",
    message: "A household member requested access to help manage your yard sale.",
    deep_link: "/Notifications",
  },
  residential_access_approved: {
    recipient: "requesting household member",
    trigger: "Yard sale owner approves household access",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Household access approved",
    message: "You can now help manage the yard sale.",
    deep_link: "/MyListings",
  },
  residential_access_denied: {
    recipient: "requesting household member",
    trigger: "Yard sale owner denies household access",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Household access denied",
    message: "Your household access request was denied.",
    deep_link: "/Notifications",
  },
  neighborhood_sale_warning_48h: {
    recipient: "Neighborhood Sale organizer and approved participants",
    trigger: "48-hour checkpoint finds sale below minimum home count",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale Warning",
    message: "The sale is below the required home minimum.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_active: {
    recipient: "Neighborhood Sale organizer and approved participants",
    trigger: "Neighborhood Sale reaches the required home count and activates",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Your Neighborhood Sale is active!",
    message: "The sale reached the required number of homes and is now live.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_participant_standalone: {
    recipient: "approved Neighborhood Sale participant",
    trigger: "Neighborhood Sale fails and approved participant listing returns to standalone visibility",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale canceled",
    message: "The sale did not reach the required number of homes. Your yard sale is no longer included with the Neighborhood Sale and will use its standalone visibility.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_payment_succeeded: {
    recipient: "Neighborhood Sale organizer",
    trigger: "24-hour lock charge succeeds",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale payment succeeded",
    message: "Payment succeeded and the sale is locked.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_payment_retry_scheduled: {
    recipient: "Neighborhood Sale organizer",
    trigger: "24-hour lock charge fails and retry is scheduled",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale payment retry scheduled",
    message: "Yardit will retry the payment.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_payment_failed_cancelled: {
    recipient: "Neighborhood Sale organizer",
    trigger: "Neighborhood Sale payment fails and the event is cancelled",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale cancelled",
    message: "The sale was cancelled because payment failed.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_fallback_applied: {
    recipient: "Neighborhood Sale organizer",
    trigger: "Neighborhood Sale misses the 5-home minimum and the organizer consented to Premium Yard Sale fallback",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Premium Yard Sale fallback applied",
    message: "Connected Yard Sale upgraded to Premium.",
    deep_link: "/ListingDetail",
  },
  neighborhood_sale_fallback_cancelled: {
    recipient: "Neighborhood Sale organizer",
    trigger: "Neighborhood Sale misses the 5-home minimum and cancels by fallback choice or unavailable Premium host listing",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Neighborhood Sale cancelled",
    message: "Neighborhood Sale cancelled with no fallback charge.",
    deep_link: "/ListingDetail",
  },
  vendor_account: {
    recipient: "vendor account owner or authorized user",
    trigger: "Vendor account lifecycle or account-level update",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Vendor account update",
    message: "Vendor account updated.",
    deep_link: "/VendorDashboard",
  },
  vendor_event: {
    recipient: "vendor event participant or organizer",
    trigger: "Vendor event update that does not require invitation acceptance",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Vendor event update",
    message: "A vendor event was updated.",
    deep_link: "/VendorEventDetail",
  },
  vendor_event_invite: {
    recipient: "invited vendor",
    trigger: "Organizer invites a vendor to a vendor event",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Vendor Event Invitation",
    message: "You were invited to join an event.",
    deep_link: "/VendorEventDetail",
  },
  event_collaboration_invite: {
    recipient: "invited vendor organization",
    trigger: "Organizer invites another organization to collaborate on an event",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Event Collaboration Invitation",
    message: "You were invited to collaborate on an event.",
    deep_link: "/VendorDashboard",
  },
  vendor_access_invite: {
    recipient: "invited vendor staff user",
    trigger: "Vendor account owner invites a user to access vendor tools",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Vendor access invitation",
    message: "You were invited to access a vendor account.",
    deep_link: "/Notifications",
  },
  vendor_checkin: {
    recipient: "users near a live vendor check-in who enabled vendor-near-me alerts",
    trigger: "Vendor checks in at a public live location",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Vendor near you",
    message: "A vendor checked in near you.",
    deep_link: "/",
  },
  vendor_subscription: {
    recipient: "users subscribed to a specific vendor",
    trigger: "Subscribed vendor checks in at a public live location",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Vendor you follow checked in",
    message: "A vendor you follow checked in.",
    deep_link: "/VendorPublicPage",
  },
  league_team_connection: {
    recipient: "team or league account owner",
    trigger: "A league connection request is created for a team",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "League connection request",
    message: "A league wants to connect with your team.",
    deep_link: "/Notifications",
  },
  league_connected: {
    recipient: "team or league account owner",
    trigger: "A league/team connection is completed",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "League connection completed",
    message: "Your team is now connected to the league.",
    deep_link: "/Notifications",
  },
  league_invite: {
    recipient: "invited league or team account owner",
    trigger: "A league or team invitation is created",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "League invitation",
    message: "You have a new league invitation.",
    deep_link: "/Notifications",
  },
  league_connection_approved: {
    recipient: "requesting league or team account owner",
    trigger: "A league connection request is approved",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "League connection approved",
    message: "Your league connection request was approved.",
    deep_link: "/Notifications",
  },
  league_invite_received: {
    recipient: "invited league or team account owner",
    trigger: "Legacy league invitation notification is received",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "League invitation",
    message: "You have a new league invitation.",
    deep_link: "/Notifications",
  },
  league_join_request: {
    recipient: "league owner",
    trigger: "A team requests to join a league",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "New league join request",
    message: "A team requested to join your league.",
    deep_link: "/LeagueTeamDashboard?tab=leagues",
  },
  league_join_approved: {
    recipient: "requesting team owner",
    trigger: "A league approves a team join request",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Join request approved",
    message: "Your league join request was approved.",
    deep_link: "/LeagueTeamDashboard?tab=schedule",
  },
  league_join_denied: {
    recipient: "requesting team owner",
    trigger: "A league denies a team join request",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Join request denied",
    message: "Your league join request was denied.",
    deep_link: "/LeagueTeamDashboard?tab=leagues",
  },
  league_team_assignment_completed: {
    recipient: "connected team account owner",
    trigger: "A league assigns an official team to a connected organization",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Team assignment completed",
    message: "A team was assigned to your league account.",
    deep_link: "/LeagueTeamDashboard?tab=my_schedule",
  },
  event_collaboration_accepted: {
    recipient: "vendor event organizer",
    trigger: "An invited organization accepts an event collaboration invitation",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Collaboration invite accepted",
    message: "An organization accepted your event collaboration invitation.",
    deep_link: "/VendorDashboard?tab=events",
  },
  join_request_sent: {
    recipient: "requesting seller",
    trigger: "Seller submits a Neighborhood Sale join request",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Join request sent",
    message: "Your Neighborhood Sale join request was sent.",
    deep_link: "/MyListings",
  },
  launch_alert: {
    recipient: "Yardit users with push enabled",
    trigger: "Master admin sends a launch alert",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "active",
    title: "Yardit launch alert",
    message: "Yardit has a launch update.",
    deep_link: "/ComingSoon",
  },
  report_received: {
    recipient: "reporting user",
    trigger: "User submits a report",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Report Received",
    message: "Your report has been received and is under review.",
    deep_link: "/Notifications",
  },
  admin_report: {
    recipient: "admin inbox",
    trigger: "Report creates or updates a case queue item",
    delivery_methods: [DELIVERY.ADMIN_INBOX],
    status: "active",
    title: "New report needs review",
    message: "A report requires administrator review.",
    deep_link: "/AdminLite?section=case_management",
  },
  admin_case: {
    recipient: "admin inbox",
    trigger: "Case assignment, escalation, submission, or review action",
    delivery_methods: [DELIVERY.ADMIN_INBOX],
    status: "active",
    title: "Case update",
    message: "A case needs administrator attention.",
    deep_link: "/AdminLite?section=case_management",
  },
  admin_note: {
    recipient: "admin inbox",
    trigger: "Admin note is created for a user, listing, case, vendor, or payment record",
    delivery_methods: [DELIVERY.ADMIN_INBOX],
    status: "active",
    title: "Admin note",
    message: "An internal note was added.",
    deep_link: "/AdminLite?section=inbox",
  },
  admin_vendor_account_auto_created: {
    recipient: "admin inbox",
    trigger: "Master admin enters Vendor Tools and the system provisions an internal vendor account",
    delivery_methods: [DELIVERY.ADMIN_INBOX],
    status: "active",
    title: "Vendor account auto-created",
    message: "A vendor account was automatically created for an admin.",
    deep_link: "/AdminLite?section=vendor",
  },
  admin_billing: {
    recipient: "admin inbox",
    trigger: "Billing log, payment audit item, or routine payment administration event",
    delivery_methods: [DELIVERY.ADMIN_INBOX],
    status: "active",
    title: "Billing item",
    message: "A billing item needs review.",
    deep_link: "/AdminLite?section=payments",
  },
  payment_webhook_failure: {
    recipient: "critical administrators",
    trigger: "Payment webhook failure or unrecoverable payment processing error",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.ADMIN_INBOX],
    status: "future",
    title: "Critical payment alert",
    message: "A payment system issue needs immediate attention.",
    deep_link: "/AdminLite?section=payments",
  },
  billing_cycles: {
    recipient: "billing/admin history",
    trigger: "Recurring billing cycle log or future renewal event",
    delivery_methods: [DELIVERY.ADMIN_INBOX],
    status: "future",
    title: "Billing cycle update",
    message: "Billing cycle event recorded.",
    deep_link: "/AdminLite?section=payments",
  },
  reserve_deposit: {
    recipient: "vendor event participant or organizer",
    trigger: "Vendor event spot/deposit reservation workflow",
    delivery_methods: [DELIVERY.PUSH, DELIVERY.BELL],
    status: "future",
    title: "Reserve deposit update",
    message: "A reserve deposit needs attention.",
    deep_link: "/VendorEventDetail",
  },
  account_created: {
    recipient: "newly registered user after account exists",
    trigger: "Successful account registration/onboarding completion",
    delivery_methods: [DELIVERY.BELL],
    status: "future",
    title: "Welcome to Yardit",
    message: "Your Yardit account was created.",
    deep_link: "/Profile",
  },
  account_update: {
    recipient: "affected user",
    trigger: "Account, profile, employee ID, or permission update",
    delivery_methods: [DELIVERY.BELL],
    status: "active",
    title: "Account update",
    message: "Your account was updated.",
    deep_link: "/Profile",
  },
};

export function getNotificationDefinition(type) {
  return NOTIFICATION_REGISTRY[type] || null;
}

export function getDeliveryMethods(type, notification = {}) {
  if (Array.isArray(notification.delivery_methods) && notification.delivery_methods.length) {
    return notification.delivery_methods;
  }
  return getNotificationDefinition(type)?.delivery_methods || [DELIVERY.BELL];
}

export function isBellNotification(notification) {
  return getDeliveryMethods(notification?.type, notification).includes(DELIVERY.BELL);
}

export function isPushNotificationType(type) {
  return getNotificationDefinition(type)?.delivery_methods?.includes(DELIVERY.PUSH) === true;
}