export const QA_CHECKLIST_VERSION = '2026.06.10-launch-grade';

export const QA_FILE_REVISIONS = {
  'pages/Home': 'qa-2026-06-10',
  'components/home/ListView': 'qa-2026-06-10',
  'components/map/ClusterGroup': 'qa-2026-06-10',
  'components/map/LocationActions': 'qa-2026-06-10',
  'components/map/RouteBuilder': 'qa-2026-06-10',
  'pages/CreateListing': 'qa-2026-06-10',
  'components/create/CreateListingResidential': 'qa-2026-06-10',
  'components/create/CreateListingNeighborhood': 'qa-2026-06-10',
  'components/create/OpenHoursFields': 'qa-2026-06-10',
  'components/create/StepOne': 'qa-2026-06-10',
  'components/create/StepTwo': 'qa-2026-06-10',
  'components/create/StepThree': 'qa-2026-06-10',
  'components/payment/ResidentialPaymentStep': 'qa-2026-06-10',
  'components/payment/ReviewPayContent': 'qa-2026-06-10',
  'components/payment/PromoCodeInput': 'qa-2026-06-10',
  'pages/MyListings': 'qa-2026-06-10',
  'components/listing/MyListingCard': 'qa-2026-06-10',
  'components/listing/MyListingActions': 'qa-2026-06-10',
  'components/listing/EditListingDialog': 'qa-2026-06-10',
  'components/listing/EditListingOpenHours': 'qa-2026-06-10',
  'components/listing/ListingUpgradeDialog': 'qa-2026-06-10',
  'pages/ListingDetail': 'qa-2026-06-10',
  'components/listing/ListingPhotoGallery': 'qa-2026-06-10',
  'components/listing/ListingShareButton': 'qa-2026-06-10',
  'components/listing/SaveListingButton': 'qa-2026-06-10',
  'components/listing/NeighborhoodSalePanel': 'qa-2026-06-10',
  'pages/Profile': 'qa-2026-06-10',
  'components/profile/AccountSetupModal': 'qa-2026-06-10',
  'components/profile/VerifiedAddressRequiredModal': 'qa-2026-06-10',
  'components/profile/UserInfoSection': 'qa-2026-06-10',
  'components/notifications/NotificationBell': 'qa-2026-06-10',
  'components/notifications/NotificationList': 'qa-2026-06-10',
  'pages/ContactSupport': 'qa-2026-06-10',
  'pages/MySupportTickets': 'qa-2026-06-10',
  'components/ReportModal': 'qa-2026-06-10',
  'pages/AdminLite': 'qa-2026-06-10',
  'components/admin/ListingManagement': 'qa-2026-06-10',
  'components/admin/SupportTicketQueue': 'qa-2026-06-10',
  'components/admin/payments/PaymentAuditDashboard': 'qa-2026-06-10',
  'components/billing/ResidentialBillingList': 'qa-2026-06-10',
  'components/billing/ResidentialReceiptDetail': 'qa-2026-06-10',
  'functions/createResidentialListingCheckout': 'qa-2026-06-10',
  'functions/createListingUpgradeCheckout': 'qa-2026-06-10',
  'functions/stripeWebhook': 'qa-2026-06-10',
  'functions/validateResidentialPromoCode': 'qa-2026-06-10',
  'functions/syncListingStatuses': 'qa-2026-06-10',
  'functions/respondToJoinRequest': 'qa-2026-06-10',
  'functions/sendJoinRequestNotification': 'qa-2026-06-10'
};

const residentialFiles = [
  'pages/CreateListing',
  'components/create/CreateListingResidential',
  'components/create/OpenHoursFields',
  'components/create/StepOne',
  'components/create/StepTwo',
  'components/create/StepThree',
  'components/payment/ResidentialPaymentStep',
  'components/payment/PromoCodeInput',
  'functions/createResidentialListingCheckout',
  'functions/stripeWebhook',
  'functions/syncListingStatuses'
];

const mapFiles = [
  'pages/Home',
  'components/home/ListView',
  'components/map/ClusterGroup',
  'components/map/LocationActions',
  'components/map/RouteBuilder',
  'components/listing/SaveListingButton',
  'components/ReportModal'
];

const myListingFiles = [
  'pages/MyListings',
  'components/listing/MyListingCard',
  'components/listing/MyListingActions',
  'components/listing/EditListingDialog',
  'components/listing/EditListingOpenHours',
  'components/listing/ListingUpgradeDialog',
  'components/billing/ResidentialReceiptDetail'
];

const detailFiles = [
  'pages/ListingDetail',
  'components/listing/ListingPhotoGallery',
  'components/listing/ListingShareButton',
  'components/listing/SaveListingButton',
  'components/listing/NeighborhoodSalePanel',
  'components/ReportModal'
];

const paymentFiles = [
  'components/payment/ResidentialPaymentStep',
  'components/payment/ReviewPayContent',
  'components/payment/PromoCodeInput',
  'components/billing/ResidentialBillingList',
  'components/billing/ResidentialReceiptDetail',
  'functions/createResidentialListingCheckout',
  'functions/createListingUpgradeCheckout',
  'functions/validateResidentialPromoCode',
  'functions/stripeWebhook'
];

const neighborhoodFiles = [
  'pages/CreateListing',
  'components/create/CreateListingNeighborhood',
  'components/listing/NeighborhoodSalePanel',
  'functions/respondToJoinRequest',
  'functions/sendJoinRequestNotification',
  'functions/syncNeighborhoodDeadlineJobs'
];

const adminFiles = [
  'pages/AdminLite',
  'components/admin/ListingManagement',
  'components/admin/SupportTicketQueue',
  'components/admin/payments/PaymentAuditDashboard',
  'components/billing/ResidentialBillingList'
];

const flow = (id, category, name, relatedFiles, items, version = '1.0') => ({
  id,
  category,
  name,
  version,
  relatedFiles,
  items: items.map((label, index) => ({ id: `${id}-${String(index + 1).padStart(3, '0')}`, label }))
});

export const QA_FLOWS = [
  flow('res-free-listing', 'Residential Listings', 'Free Listing User Journey', residentialFiles, [
    'Open Yardit as a verified residential user.',
    'Confirm the Home map screen loads before starting the listing flow.',
    'Click the Post Sale button in the top navigation.',
    'Confirm the Create Listing screen opens.',
    'Confirm the listing type choices are visible.',
    'Click the Yard Sale or Residential listing option.',
    'Confirm the residential listing form opens.',
    'Confirm the title field is visible.',
    'Leave the title field blank.',
    'Click Next.',
    'Confirm the required title validation message appears.',
    'Enter a clear yard sale title.',
    'Confirm the title remains in the field after typing.',
    'Enter a detailed description.',
    'Confirm the description accepts normal sale details without clipping text.',
    'Select at least one category.',
    'Confirm the selected category badge or checkbox shows as selected.',
    'Click the address search field.',
    'Enter the test street address.',
    'Select the suggested address result.',
    'Confirm the address, city, state, ZIP, and map pin update.',
    'Click Next.',
    'Confirm the date selection screen appears.',
    'Select a valid sale start date.',
    'Select a valid sale end date.',
    'Confirm the selected date range is displayed.',
    'Select open time.',
    'Select close time after the open time.',
    'Confirm no open/close validation error appears.',
    'Click Next.',
    'Confirm the tier selection screen appears.',
    'Select Free Listing.',
    'Confirm the price shows $0 or free.',
    'Click Preview Listing.',
    'Confirm the preview shows title, description, address, dates, open hours, category, and free tier badge.',
    'Click Publish or Save Listing.',
    'Confirm no checkout screen opens for the free listing.',
    'Confirm the final success message appears.',
    'Open My Listings.',
    'Confirm the new free listing appears in the correct tab.',
    'Open the Home map.',
    'Confirm the free listing appears on the map during its public visibility window.',
    'Open list view.',
    'Confirm the free listing appears in list view with matching title and schedule.'
  ]),
  flow('res-featured-listing', 'Residential Listings', 'Featured Listing User Journey', residentialFiles, [
    'Open Yardit as a verified residential user.',
    'Click Post Sale.',
    'Click the residential Yard Sale option.',
    'Enter a unique Featured listing title.',
    'Enter a description with several sale item examples.',
    'Select categories.',
    'Select the sale address from address search.',
    'Confirm the map pin lands on the selected address.',
    'Select valid start and end dates.',
    'Select valid open and close hours.',
    'Click Next until the tier screen appears.',
    'Select Featured Listing.',
    'Confirm the Featured benefits display.',
    'Confirm the Featured price displays before checkout.',
    'Click Continue to Payment.',
    'Confirm the payment review screen opens.',
    'Confirm listing title, tier, price, and non-refundable notice display.',
    'Click checkout.',
    'Confirm the Stripe checkout page opens.',
    'Complete payment with an approved test card or live payment method.',
    'Confirm the success return screen loads.',
    'Open My Listings.',
    'Confirm the listing tier badge says Featured.',
    'Open the Home map during the visibility window.',
    'Confirm the marker uses Featured styling.',
    'Open listing detail.',
    'Confirm the payment receipt or billing section is available to the owner.',
    'Confirm a PaymentTransaction record appears in billing views for the listing.'
  ]),
  flow('res-premium-listing', 'Residential Listings', 'Premium Listing User Journey', residentialFiles, [
    'Open Yardit as a verified residential user.',
    'Click Post Sale.',
    'Choose the residential Yard Sale option.',
    'Enter a Premium listing title.',
    'Enter a detailed description.',
    'Select multiple categories.',
    'Upload listing photos if the photo step is available.',
    'Confirm uploaded photos show thumbnails.',
    'Select the sale address and confirm the map pin location.',
    'Select a multi-day date range.',
    'Select open and close hours.',
    'Click Next until tier selection appears.',
    'Select Premium Listing.',
    'Confirm Premium benefits display.',
    'Confirm Premium price displays.',
    'If early visibility options appear, select the allowed early visibility days.',
    'Confirm the coming soon or early visibility summary updates.',
    'Click Continue to Payment.',
    'Confirm payment review displays Premium tier and total.',
    'Complete checkout.',
    'Confirm success screen appears.',
    'Open My Listings.',
    'Confirm Premium badge appears on the listing card.',
    'Open Home map before active open hours but inside early visibility.',
    'Confirm the listing shows as Coming Soon or early visibility instead of Open.',
    'Open Home map during active open hours.',
    'Confirm the listing shows as active with Premium styling.',
    'Open Listing Detail.',
    'Confirm photos, Premium badge, selected dates, open hours, share, bookmark, report, and route actions appear.'
  ]),
  flow('res-open-close-hours', 'Residential Listings', 'Open/Close Hours Journey', residentialFiles, [
    'Start a residential listing creation flow.',
    'Navigate to the schedule or open hours step.',
    'Confirm the open time field is visible.',
    'Confirm the close time field is visible.',
    'Leave open time blank if the field allows clearing.',
    'Click Next.',
    'Confirm an open time validation message appears.',
    'Enter an open time.',
    'Leave close time blank if the field allows clearing.',
    'Click Next.',
    'Confirm a close time validation message appears.',
    'Enter a close time earlier than the open time.',
    'Click Next.',
    'Confirm a validation message explains close time must be after open time.',
    'Enter a valid close time after open time.',
    'Click Next.',
    'Confirm the flow advances.',
    'Open preview.',
    'Confirm the open and close times display exactly as selected.',
    'Save the listing.',
    'Open My Listings.',
    'Confirm the listing card displays both date range and Open/Close visibility hours.',
    'Open public listing detail.',
    'Confirm the same visibility hours display there.',
    'Open Home map outside the daily visibility hours.',
    'Confirm the listing is hidden or marked not currently open according to current app rules.',
    'Open Home map inside the daily visibility hours.',
    'Confirm the listing appears as active.'
  ]),
  flow('res-edit-upgrade-expire-relist', 'Residential Listings', 'Edit, Upgrade, Expiration, and Relist Journey', [...residentialFiles, ...myListingFiles], [
    'Open My Listings as the listing owner.',
    'Click the Active tab.',
    'Find a residential listing card.',
    'Confirm the card shows title, address, date range, open hours, tier badge, and status badge.',
    'Click Edit.',
    'Confirm the edit modal opens.',
    'Change the title.',
    'Change the description.',
    'Change categories if available.',
    'Change open and close hours.',
    'Click Save.',
    'Confirm the modal closes or shows saved state.',
    'Confirm the card updates with the edited values.',
    'Open the listing detail page.',
    'Confirm the edited values display on detail.',
    'Return to My Listings.',
    'Click Upgrade.',
    'Confirm the upgrade modal opens.',
    'Select Featured or Premium upgrade.',
    'Confirm upgrade price and tier benefits display.',
    'Click Continue to Payment.',
    'Cancel the checkout before paying.',
    'Confirm the listing tier does not change after canceled checkout.',
    'Start upgrade again.',
    'Complete payment successfully.',
    'Confirm the listing tier updates only after payment success.',
    'Open billing or receipt.',
    'Confirm upgrade transaction appears.',
    'Use an expired listing or adjust test data to an expired listing.',
    'Open My Listings Expired tab.',
    'Confirm the expired listing appears in Expired.',
    'Confirm expired listing is not visible on the public map or list view.',
    'Click Relist.',
    'Confirm relist flow opens with prior listing details prefilled where intended.',
    'Select new valid dates and open hours.',
    'Save or pay as required.',
    'Confirm relisted listing appears in Active or Scheduled according to new dates.'
  ]),
  flow('res-preview-owner-map-list', 'Residential Listings', 'Preview, Owner Preview, Map Visibility, and List Visibility Journey', [...residentialFiles, ...mapFiles, ...detailFiles], [
    'Create or open an existing residential listing as the owner.',
    'Click Preview Listing before final publish if preview is available.',
    'Confirm preview includes title.',
    'Confirm preview includes description.',
    'Confirm preview includes photos or photo placeholder.',
    'Confirm preview includes address.',
    'Confirm preview includes selected date range.',
    'Confirm preview includes open and close hours.',
    'Confirm preview includes category badges.',
    'Confirm preview includes tier badge.',
    'Publish or save the listing.',
    'Open Home map as the owner.',
    'Turn on Owner Preview toggle if available.',
    'Confirm owner-only scheduled or hidden preview behavior matches the toggle label.',
    'Turn off Owner Preview toggle.',
    'Confirm only public eligible listings remain visible.',
    'Open the map during a listing visible window.',
    'Confirm the listing marker appears.',
    'Click the marker.',
    'Confirm the popup opens.',
    'Open list view.',
    'Confirm the same listing appears in list view.',
    'Apply a category filter matching the listing.',
    'Confirm the listing remains visible.',
    'Apply a category filter that does not match.',
    'Confirm the listing disappears from list and map results.',
    'Clear filters.',
    'Confirm the listing returns.'
  ]),
  flow('neighborhood-create-organizer', 'Neighborhood Sales', 'Create Neighborhood Sale and Organizer Setup Journey', neighborhoodFiles, [
    'Open Yardit as a verified residential user.',
    'Click Post Sale.',
    'Confirm listing type options appear.',
    'Click Neighborhood Sale.',
    'Confirm Neighborhood Sale intro or setup screen opens.',
    'Confirm organizer setup instructions are visible.',
    'Enter neighborhood sale title.',
    'Enter neighborhood sale description.',
    'Select organizer mode if prompted.',
    'Choose participating organizer mode.',
    'Confirm organizer listing fields appear.',
    'Enter organizer listing sale details.',
    'Enter or confirm host address.',
    'Confirm host address map preview appears.',
    'Click radius validation or continue.',
    'Confirm radius validation succeeds for the host location.',
    'Select sale dates.',
    'Select open and close hours.',
    'Confirm the participant collection or billing summary screen appears.',
    'Confirm base neighborhood price displays.',
    'Confirm per-home pricing displays.',
    'Confirm additional due shows zero or correct calculated amount before participants join.',
    'Click Save or Continue.',
    'Confirm the neighborhood sale is created.',
    'Open My Listings.',
    'Confirm the organizer neighborhood sale card appears.',
    'Confirm the HOST badge appears on organizer card.',
    'Confirm the Upgrade button is not shown for the neighborhood sale card.',
    'Open listing detail.',
    'Confirm organizer view shows invite link, participant section, billing section, and activation status.'
  ]),
  flow('neighborhood-join-approval', 'Neighborhood Sales', 'Ask To Join, Approve, Deny, and Remove Participant Journey', neighborhoodFiles, [
    'Open a public neighborhood sale detail page as a different verified user.',
    'Confirm the public view shows neighborhood sale title, organizer context, dates, and join action.',
    'Click Ask To Join or Join Neighborhood Sale.',
    'Confirm join flow opens.',
    'Enter participant sale title.',
    'Enter participant description.',
    'Enter participant address inside the allowed radius.',
    'Click radius validation or continue.',
    'Confirm the address is accepted as within range.',
    'Select participant sale categories.',
    'Confirm participant dates and hours match or align with organizer event rules.',
    'Submit join request.',
    'Confirm pending message appears to the participant.',
    'Log in as the organizer.',
    'Open the neighborhood sale organizer view.',
    'Confirm the pending participant appears in the approval list.',
    'Click Approve on the pending participant.',
    'Confirm approval confirmation appears if present.',
    'Confirm participant status changes to approved.',
    'Confirm participant home count updates.',
    'Confirm billing or additional due updates if pricing changes.',
    'Open public map during visibility window.',
    'Confirm approved participant pin appears.',
    'Create or use a second pending participant request.',
    'Click Deny.',
    'Enter denial reason if requested.',
    'Confirm denied participant no longer appears as approved.',
    'Confirm denied participant does not appear publicly.',
    'Use an approved participant.',
    'Click Remove Participant.',
    'Enter removal reason if requested.',
    'Confirm participant status changes to removed or denied according to app rules.',
    'Confirm participant pin leaves public map and list view.',
    'Confirm participant receives or can view the status change notification.'
  ]),
  flow('neighborhood-billing-activation-public', 'Neighborhood Sales', 'Billing, Activation, Coming Soon, Public View, and Organizer View Journey', [...neighborhoodFiles, ...paymentFiles, ...detailFiles], [
    'Open the organizer neighborhood sale detail page.',
    'Confirm organizer-only management controls are visible to the organizer.',
    'Confirm public users do not see organizer-only approval controls.',
    'Open the Billing section.',
    'Confirm total current cost is visible even if transaction history is collapsed.',
    'Expand Billing transaction history.',
    'Confirm prior payment transactions display with amount, status, and date.',
    'Add or approve a participant that changes home count.',
    'Return to Billing.',
    'Confirm Additional Due equals current total cost minus paid amounts.',
    'Click payment action if additional due is required.',
    'Confirm checkout opens with neighborhood sale amount.',
    'Complete or cancel checkout according to the test case.',
    'Confirm successful payment updates billing status.',
    'Confirm canceled payment does not activate unpaid benefits.',
    'Set or use a future neighborhood sale date.',
    'Open public map before active sale day but inside coming soon rules.',
    'Confirm neighborhood sale displays as Coming Soon if eligible.',
    'Confirm coming soon badge or status appears.',
    'Open public map during active hours.',
    'Confirm organizer sale and approved participant homes appear.',
    'Open public listing detail as non-owner.',
    'Confirm public view hides billing and approval controls.',
    'Open organizer view as organizer.',
    'Confirm organizer view shows participants, approvals, billing, invite link, and activation state.'
  ]),
  flow('map-home-discovery', 'Map / Home', 'Initial Load, Search, Filters, Location, Zoom, Clustering, and Pin Selection Journey', mapFiles, [
    'Open Yardit Home.',
    'Confirm the map container loads.',
    'Confirm map tiles render without blank gray areas after loading.',
    'Confirm current location button appears.',
    'Confirm search input appears.',
    'Confirm filter button or filter controls appear.',
    'Confirm list view toggle appears if available.',
    'Click the search field.',
    'Enter a city, ZIP, or address.',
    'Select a search result or press search.',
    'Confirm the map moves to the searched area.',
    'Confirm matching results update.',
    'Click current location.',
    'When browser asks for permission, click Allow.',
    'Confirm map centers near the device location.',
    'Repeat current location with permission denied in a separate browser profile.',
    'Confirm the app shows a useful permission message and does not crash.',
    'Open filters.',
    'Select residential listing filter.',
    'Confirm residential pins remain and unrelated pins hide.',
    'Select neighborhood sale filter.',
    'Confirm neighborhood sale pins remain and unrelated pins hide.',
    'Select coming soon visibility filter if available.',
    'Confirm eligible coming soon listings display according to rules.',
    'Clear filters.',
    'Confirm full eligible result set returns.',
    'Zoom out until nearby listings cluster.',
    'Confirm cluster badge count appears.',
    'Click a cluster.',
    'Confirm the map zooms or expands clustered listings.',
    'Click an individual pin.',
    'Confirm popup opens with title, date, address or area, tier/status badge, and action buttons.',
    'Click outside the popup or close button.',
    'Confirm popup closes.'
  ]),
  flow('map-actions-route-save-report', 'Map / Home', 'Popup Actions, Add Stop, Bookmark, Report, Route Builder, and Owner Preview Journey', mapFiles, [
    'Open Home map with at least one eligible listing visible.',
    'Click a listing pin.',
    'Confirm popup action buttons appear.',
    'Click View Details.',
    'Confirm listing detail opens for the selected listing.',
    'Return to Home map.',
    'Click the same or another listing pin.',
    'Click Add Stop or Join the Hunt action.',
    'Confirm the listing is added to the route or hunt list.',
    'Confirm route builder panel or route indicator updates.',
    'Add a second stop.',
    'Confirm stop order or count updates.',
    'Remove one stop.',
    'Confirm route updates immediately.',
    'Click Bookmark or Save on a listing.',
    'If logged out, confirm login prompt opens before saving.',
    'Log in if needed and repeat save.',
    'Confirm bookmark icon changes to saved state.',
    'Open Profile or saved listings area.',
    'Confirm saved listing appears.',
    'Return to map and unsave the listing.',
    'Confirm saved state is removed.',
    'Click Report on a popup or detail card.',
    'Confirm report modal opens.',
    'Close report modal without submitting.',
    'Confirm user returns to map without losing map position.',
    'As listing owner, open Home map.',
    'Use Owner Preview toggle if available.',
    'Confirm owner preview changes visibility only for owner preview context.',
    'Turn Owner Preview off.',
    'Confirm public visibility rules are restored.'
  ]),
  flow('my-listings-management', 'My Listings', 'Tabs, Statuses, Search, Filters, Card Actions, Receipt, and Billing Journey', myListingFiles, [
    'Open My Listings as a logged-in user with multiple listing statuses.',
    'Confirm tabs are visible.',
    'Click Active tab.',
    'Confirm active listings appear.',
    'Confirm each active card shows badges at the top on mobile.',
    'Confirm each active card shows action buttons at the bottom on mobile.',
    'Click Scheduled tab.',
    'Confirm scheduled listings appear and active listings hide.',
    'Click Expired tab.',
    'Confirm expired listings appear.',
    'Click Hidden tab if present.',
    'Confirm hidden listings appear only to owner/admin.',
    'Click Canceled tab if present.',
    'Confirm canceled listings appear.',
    'Use search field to enter part of a listing title.',
    'Confirm matching cards remain.',
    'Clear search.',
    'Open filters.',
    'Filter by listing type.',
    'Confirm only matching cards remain.',
    'Filter by tier or status if available.',
    'Confirm cards update.',
    'Click View Listing on a card.',
    'Confirm listing detail opens.',
    'Return to My Listings.',
    'Click Edit on an editable card.',
    'Confirm edit modal opens.',
    'Close edit modal.',
    'Click Upgrade on an eligible residential card.',
    'Confirm upgrade modal opens.',
    'Confirm neighborhood sale cards do not show Upgrade.',
    'Click Receipt or Billing on a paid listing.',
    'Confirm receipt displays listing name, amount, date, payment status, and transaction ID if available.',
    'Close receipt and confirm My Listings remains usable.'
  ]),
  flow('listing-detail-complete', 'Listing Detail', 'All Sections, Photos, Times, Dates, Badges, Report, Share, Bookmark, and Route Actions Journey', detailFiles, [
    'Open a residential listing detail page from map or list view.',
    'Confirm the page or detail card loads without errors.',
    'Confirm title section appears.',
    'Confirm photo gallery appears or placeholder appears when no photos exist.',
    'Click the first photo if gallery supports opening.',
    'Confirm photo viewer opens or photo enlarges.',
    'Close the photo viewer.',
    'Confirm description section appears.',
    'Confirm category badges appear.',
    'Confirm tier badge appears.',
    'Confirm status badge appears.',
    'Confirm selected date range displays.',
    'Confirm open and close visibility hours display.',
    'Confirm address or location section displays according to privacy rules.',
    'Click Share.',
    'Confirm share dialog, copy action, or native share opens.',
    'Complete copy/share action.',
    'Confirm success feedback appears if provided.',
    'Click Bookmark.',
    'Confirm saved state changes.',
    'Click Bookmark again.',
    'Confirm saved state is removed.',
    'Click Add Stop or route action.',
    'Confirm listing is added to the route builder.',
    'Click Report.',
    'Confirm report modal opens.',
    'Close modal.',
    'Open a neighborhood sale detail page.',
    'Confirm participant section appears.',
    'Confirm organizer/public controls appear according to current user role.',
    'Open an owner-owned detail page.',
    'Confirm owner-only edit, billing, or management actions appear.',
    'Open the same detail page as non-owner.',
    'Confirm owner-only controls are hidden.'
  ]),
  flow('profile-auth-settings', 'Profile', 'Registration, Login, Logout, Name, Terms, Address, Contact, and Settings Journey', ['pages/Profile', 'components/profile/AccountSetupModal', 'components/profile/VerifiedAddressRequiredModal', 'components/profile/UserInfoSection', 'pages/Settings', 'layout'], [
    'Open Yardit while logged out.',
    'Click Log In / Sign Up.',
    'Confirm authentication screen opens.',
    'Start registration with a new email.',
    'Confirm required auth fields validate when blank.',
    'Complete registration.',
    'Confirm new user returns to Yardit.',
    'Confirm name collection or account setup modal opens if required.',
    'Leave required name field blank.',
    'Click Save or Continue.',
    'Confirm validation message appears.',
    'Enter name.',
    'Accept terms if terms acceptance appears.',
    'Confirm account setup saves.',
    'Click Post Sale before verified address exists.',
    'Confirm verified address required modal opens.',
    'Click Add Address or Go to Profile.',
    'Confirm Profile page opens.',
    'Enter primary address.',
    'Select address suggestion or confirm address.',
    'Confirm address confirmation screen or map appears.',
    'Save confirmed address.',
    'Confirm address shows as verified or confirmed.',
    'Change address if reverification controls exist.',
    'Confirm address reverification is required after changing address.',
    'Confirm email displays and is not accidentally overwritten by profile edits.',
    'Confirm no phone number is required for creating residential listings or receiving SMS.',
    'If an optional phone field exists in Profile, leave it blank and confirm Profile can still save.',
    'Open Settings.',
    'Change a safe preference.',
    'Save settings.',
    'Refresh page.',
    'Confirm setting persists.',
    'Open account menu.',
    'Click Logout.',
    'Confirm user is logged out and routed to the expected public or Coming Soon page.',
    'Click Log In / Sign Up again.',
    'Use forgot password link if available.',
    'Confirm forgot password screen or provider flow opens without app crash.',
    'Log back in.',
    'Confirm My Listings and Profile data remain available.'
  ]),
  flow('notifications', 'Notifications', 'Bell Icon, Popup, View All, Read, Unread, Navigation, and Auto Close Journey', ['components/notifications/NotificationBell', 'components/notifications/NotificationList', 'pages/Notifications'], [
    'Log in as a user with at least one notification.',
    'Confirm notification bell icon appears in the top navigation.',
    'Confirm unread indicator or badge appears when unread notifications exist.',
    'Click the bell icon.',
    'Confirm notification popup opens.',
    'Confirm unread notification is visually different from read notification.',
    'Click a notification row.',
    'Confirm the app navigates to the related listing, support ticket, or relevant page when configured.',
    'Return to notifications popup.',
    'Mark a notification as read if action exists.',
    'Confirm unread badge count decreases.',
    'Open View All.',
    'Confirm full notifications page opens.',
    'Confirm notifications are listed with title, message, date, and read status.',
    'Mark all as read if action exists.',
    'Confirm unread count clears.',
    'Open bell popup again.',
    'Click outside the popup.',
    'Confirm popup auto closes.',
    'Open popup on mobile.',
    'Confirm popup fits screen and can be closed.'
  ]),
  flow('support-ticketing', 'Support', 'Contact Support, Categories, Routing, Ticket Creation, Status, and History Journey', ['pages/ContactSupport', 'pages/MySupportTickets', 'components/admin/SupportTicketQueue'], [
    'Open Contact Support.',
    'Confirm support category options appear.',
    'Select Residential category.',
    'Confirm residential routing or category label appears.',
    'Leave required name or email field blank.',
    'Click Submit.',
    'Confirm validation message appears.',
    'Enter name.',
    'Enter email.',
    'Enter issue description.',
    'Submit without optional photo.',
    'Confirm ticket creation success message appears.',
    'Confirm ticket number appears if provided.',
    'Open My Support Tickets.',
    'Confirm the new ticket appears.',
    'Confirm ticket status appears.',
    'Open ticket details if available.',
    'Confirm description and category are preserved.',
    'Create a second ticket with a photo if photo upload is available.',
    'Confirm photo preview appears before submit.',
    'Submit ticket.',
    'Log in as admin.',
    'Open Support Queue.',
    'Confirm both tickets appear in the correct queue.',
    'Change ticket status to In Review.',
    'Confirm status saves.',
    'Return as user.',
    'Confirm ticket history shows updated status.'
  ]),
  flow('report-flow', 'Report Flow', 'Report Listing, Report User, Validation, Submission, and Admin Review Journey', ['components/ReportModal', 'functions/createCaseFromReport', 'pages/AdminLite', 'components/admin/SupportTicketQueue'], [
    'Open a public listing detail page as a logged-in non-owner.',
    'Click Report.',
    'Confirm report modal opens.',
    'Confirm reason options appear.',
    'Click Submit without selecting a reason.',
    'Confirm validation message appears.',
    'Select a report reason.',
    'Leave details blank if details are required.',
    'Click Submit.',
    'Confirm details validation appears when required.',
    'Enter report details.',
    'Attach a screenshot or photo if report photo upload exists.',
    'Confirm attachment preview appears.',
    'Submit report.',
    'Confirm success confirmation appears.',
    'Confirm modal closes or displays final result.',
    'Confirm listing report count or related status updates where visible.',
    'Open admin dashboard.',
    'Open reports, cases, or support queue.',
    'Confirm the report appears with listing ID, reporter, reason, details, and date.',
    'Open the report review item.',
    'Confirm admin can view submitted details without losing attachment.',
    'Change admin review status.',
    'Confirm status change saves.',
    'If admin hides or suspends the listing, open public map.',
    'Confirm hidden or suspended listing no longer appears publicly.'
  ]),
  flow('payments-billing', 'Payments', 'Checkout, Promo Codes, Success, Cancel, Retry, Receipts, Transactions, and Billing Views Journey', paymentFiles, [
    'Start a paid Featured or Premium residential listing checkout.',
    'Confirm payment review screen opens before Stripe checkout.',
    'Confirm listing title displays on review screen.',
    'Confirm selected tier displays on review screen.',
    'Confirm total amount displays on review screen.',
    'Enter an invalid promo code if promo field exists.',
    'Click Apply.',
    'Confirm invalid promo message appears.',
    'Enter a valid percentage promo code if available.',
    'Click Apply.',
    'Confirm discount amount and final total update.',
    'Remove or replace promo code if control exists.',
    'Confirm total recalculates.',
    'Click Checkout.',
    'Confirm Stripe checkout opens.',
    'Cancel checkout.',
    'Confirm app returns to cancel or listing flow state.',
    'Confirm paid tier is not granted after cancellation.',
    'Click Retry Payment if available.',
    'Confirm checkout can be started again.',
    'Complete payment successfully.',
    'Confirm success screen appears.',
    'Confirm listing payment status changes to paid.',
    'Open My Listings.',
    'Click Receipt or Billing.',
    'Confirm receipt includes amount, tier, listing, date, status, and transaction identifiers where available.',
    'Open admin billing or payment audit view.',
    'Confirm matching PaymentTransaction appears.',
    'Confirm duplicate webhook or refresh does not create duplicate successful transactions.'
  ]),
  flow('admin-residential-neighborhood-users', 'Admin', 'Dashboard, Residential Listings, Neighborhood Sales, Users, Search, Filters, and Status Changes Journey', adminFiles, [
    'Log in as an authorized admin.',
    'Open Admin Login or Admin Lite.',
    'Enter Employee ID.',
    'Enter PIN.',
    'Click login.',
    'Confirm admin dashboard opens.',
    'Confirm dashboard summary cards load.',
    'Open Residential Listings management.',
    'Confirm listing table or cards load.',
    'Use listing search by title or listing number.',
    'Confirm matching listing appears.',
    'Use status filter.',
    'Confirm filtered statuses appear.',
    'Open a residential listing detail from admin.',
    'Confirm admin can view owner, status, listing detail, and payment context.',
    'Change a safe test listing status to hidden or under review.',
    'Confirm status change saves.',
    'Open public map as non-admin.',
    'Confirm hidden or under review listing is not public.',
    'Return to admin.',
    'Restore the test listing status if required.',
    'Open Neighborhood Sales management.',
    'Search for a neighborhood sale.',
    'Open organizer view or admin detail.',
    'Confirm participants, billing summary, activation state, and public status are visible.',
    'Open Users management.',
    'Search for a user by email or name.',
    'Open user detail.',
    'Confirm user listings, reports, notes, and activity sections load according to admin permissions.'
  ]),
  flow('admin-support-reports-billing-qr-locked', 'Admin', 'Support Queue, Reports, Billing, Transactions, QR Code Lock, Listing Detail, and Approval Actions Journey', adminFiles, [
    'Open Admin dashboard as an authorized admin.',
    'Open Support Queue.',
    'Confirm open tickets appear.',
    'Filter support tickets by status.',
    'Confirm matching tickets remain.',
    'Open a support ticket.',
    'Confirm ticket details, requester, category, photos, and history are visible.',
    'Change ticket status.',
    'Confirm status saves.',
    'Open Reports or Case Management.',
    'Confirm reported listings or users appear.',
    'Open a report.',
    'Confirm report reason, details, related listing, and reporter data display.',
    'Choose a safe review or approval action on a test report.',
    'Confirm action saves and audit/history updates.',
    'Open Billing or Transactions.',
    'Search by listing ID, user email, or transaction ID.',
    'Confirm matching payment transaction appears.',
    'Open transaction detail if available.',
    'Confirm amount, status, Stripe IDs, user, listing, and processed date display.',
    'Open an admin listing detail page.',
    'Confirm listing badges, status, payment state, owner, dates, and actions display.',
    'Open Assisted Listings or QR Codes area only for a read-only smoke check.',
    'Confirm QR code records or QR status are visible if the existing screen supports it.',
    'Do not regenerate, edit, or change any assisted listing QR code during this QA flow.',
    'Confirm the assisted listing QR workflow remains locked and unchanged after admin QA.'
  ]),
  flow('approve-flow', 'Approval', 'Approve Flow Sign-off Journey', ['components/checklist/LaunchChecklistContent', 'components/checklist/QAFlowCard', 'components/checklist/qaChecklistData.js', 'lib/launchChecklistStorage.js'], [
    'Open the Yardit QA Checklist System.',
    'Select the flow that is ready for approval.',
    'Confirm every checklist item in that flow has been tested.',
    'Confirm every required item has Pass selected.',
    'Confirm failed items include notes explaining the failure.',
    'Confirm screenshot optional boxes are checked only when screenshots were captured or intentionally requested.',
    'Confirm Tested By is filled for each completed item.',
    'Confirm Tested Date is filled for each completed item.',
    'Review the related files list for the flow.',
    'Enter approver name in the Approved By field.',
    'Click Approve Flow.',
    'Confirm Flow Name is saved.',
    'Confirm Version is saved.',
    'Confirm Approved By is saved.',
    'Confirm Approved Date is saved.',
    'Confirm Related Files are saved.',
    'Refresh the page.',
    'Confirm approval still displays after refresh.',
    'Change a related file revision in the QA file map during a controlled test.',
    'Reload the checklist.',
    'Confirm the approved flow changes to Needs Retest.',
    'Confirm the changed file is shown.',
    'Confirm the potentially affected flow name is shown.'
  ]),
  flow('freeze-flow', 'Approval', 'Freeze Flow Launch Lock Journey', ['components/checklist/LaunchChecklistContent', 'components/checklist/QAFlowCard', 'components/checklist/qaChecklistData.js'], [
    'Open the Yardit QA Checklist System.',
    'Confirm Vendor Dashboard flows are not included.',
    'Confirm assisted listing QR code implementation files are not changed by this QA checklist update.',
    'Review all Residential Listing flows.',
    'Confirm all critical Residential flows are approved or marked ready.',
    'Review all Neighborhood Sale flows.',
    'Confirm all critical Neighborhood flows are approved or marked ready.',
    'Review all Map and Home flows.',
    'Confirm all critical Map and Home flows are approved or marked ready.',
    'Review My Listings and Listing Detail flows.',
    'Confirm all critical owner-management flows are approved or marked ready.',
    'Review Profile, Notifications, Support, Report, Payments, and Admin flows.',
    'Confirm each launch-critical flow has an approver and approval date.',
    'Export or download the QA checklist.',
    'Save the exported checklist in the launch evidence folder.',
    'Identify all related files listed by approved flows.',
    'Freeze or lock approved files according to Base44 file-level locking process.',
    'Record the frozen file list in launch notes.',
    'If any frozen related file must change later, mark the affected flow as Needs Retest before launch.',
    'Confirm the Launch Verdict shows no unapproved critical blocker before proceeding.'
  ])
];