const residentialBaseFiles = [
  'pages/CreateListing',
  'components/create/CreateListingResidential',
  'components/create/StepOne',
  'components/create/StepTwo',
  'components/create/StepThree',
  'components/create/OpenHoursFields',
  'components/payment/ResidentialPaymentStep',
  'pages/MyListings',
  'components/listing/MyListingCard',
  'components/listing/EditListingDialog',
  'components/listing/ListingUpgradeDialog',
  'pages/ListingDetail',
  'pages/Home',
  'components/home/ListView',
  'lib/listingVisibility.js',
  'lib/listViewPipeline.js',
];

const neighborhoodBaseFiles = [
  'pages/CreateListing',
  'components/create/CreateListingNeighborhood',
  'components/create/NeighborhoodSaleIntroModal',
  'components/create/NeighborhoodJoinDialogs',
  'components/create/NeighborhoodCoHostSelector',
  'components/listing/NeighborhoodSalePanel',
  'pages/JoinNeighborhoodSale',
  'pages/MyListings',
  'pages/ListingDetail',
  'functions/respondToJoinRequest',
  'functions/createNeighborhoodSaleSetup',
  'functions/neighborhoodSaleSetupCheckout',
  'functions/cancelNeighborhoodSale',
  'lib/neighborhoodSalePricing.js',
  'lib/neighborhoodSaleState.js',
];

const mapBaseFiles = [
  'pages/Home',
  'components/home/ListView',
  'components/home/ListFilterModal',
  'components/map/ClusterGroup',
  'components/map/QuickMapFilters',
  'components/map/RouteBuilder',
  'components/map/CheckInButton',
  'components/map/HiddenListingsOverlay',
  'lib/listingVisibility.js',
  'lib/listViewPipeline.js',
];

const myListingsBaseFiles = [
  'pages/MyListings',
  'components/listing/MyListingCard',
  'components/listing/MyListingActions',
  'components/listing/EditListingDialog',
  'components/listing/ListingUpgradeDialog',
  'components/billing/ResidentialBillingList',
  'lib/myListingsHelpers.js',
];

const detailBaseFiles = [
  'pages/ListingDetail',
  'components/listing/ListingPhotoGallery',
  'components/listing/ListingShareButton',
  'components/listing/SaveListingButton',
  'components/listing/listingDisplay',
  'components/listing/listingDetailContent',
  'components/ReportModal',
];

const profileBaseFiles = [
  'pages/Profile',
  'pages/AccountOptions',
  'components/profile/AccountSetupModal',
  'components/profile/VerifiedAddressRequiredModal',
  'components/profile/UserInfoSection',
  'components/create/PrimaryAddressVerificationModal',
  'components/create/PrimaryAddressVerificationGate',
  'lib/AuthContext.jsx',
  'hooks/useGuestGuard.js',
];

const notificationBaseFiles = [
  'components/notifications/NotificationBell',
  'components/notifications/NotificationList',
  'pages/Notifications',
];

const supportBaseFiles = [
  'pages/ContactSupport',
  'pages/MySupportTickets',
  'components/admin/SupportTicketQueue',
  'pages/CaseManagement',
  'functions/createCaseFromReport',
];

const paymentBaseFiles = [
  'components/payment/ResidentialPaymentStep',
  'components/payment/PromoCodeInput',
  'components/profile/PaymentHistory',
  'components/billing/ResidentialBillingList',
  'components/billing/ResidentialReceiptDetail',
  'functions/createResidentialListingCheckout',
  'functions/createListingUpgradeCheckout',
  'functions/residentialStripeCheckout',
  'functions/stripeWebhook',
  'functions/validateResidentialPromoCode',
  'functions/linkPaymentTransactionsForListing',
];

const adminBaseFiles = [
  'pages/AdminLite',
  'components/admin/AdminLiteDashboard',
  'components/admin/ListingManagement',
  'components/admin/UserManagement',
  'components/admin/SupportTicketQueue',
  'components/admin/payments/PaymentAuditDashboard',
  'components/admin/AdminLogsTab',
  'components/admin/system-health/SystemHealthDashboard',
  'functions/paymentAuditScan',
  'functions/runSystemHealthScan',
];

const makeItems = (prefix, items) => items.map((label, index) => ({
  id: `${prefix}-${String(index + 1).padStart(3, '0')}`,
  label,
  critical: index < 8,
}));

const flow = ({ category, name, slug, version = '1.0.0', relatedFiles, items }) => ({
  id: slug,
  category,
  name,
  version,
  relatedFiles,
  items: makeItems(slug, items),
});

const residentialStart = [
  'Open Yardit in a clean browser session.',
  'Confirm the Home map screen loads without a blank page or error banner.',
  'Confirm the top navigation shows the Yardit logo, Map button, Checklist button, and Post Sale button.',
  'Click Post Sale.',
  'If login is required, confirm the login or sign-up prompt opens before the create listing flow.',
  'Log in as a test residential seller.',
  'Click Post Sale again after login completes.',
  'Confirm the verified address requirement modal appears if the test account has no confirmed primary address.',
  'Confirm the modal explains that a verified primary address is required before posting a sale.',
  'Click the modal action that sends the user to Profile.',
  'Add or confirm the primary address for the test account.',
  'Return to Home and click Post Sale.',
  'Confirm the listing type selection screen opens.',
  'Confirm Yard Sale, Neighborhood Sale, and Event options are visible.',
  'Click Yard Sale.',
  'Confirm the Residential Create Listing flow opens.',
];

const residentialDetails = [
  'Confirm the title field is visible.',
  'Leave the title field blank.',
  'Click Next or Continue.',
  'Confirm a validation message appears telling the user the title is required.',
  'Enter a clear test title.',
  'Confirm the typed title remains visible in the field.',
  'Confirm the description field is visible.',
  'Enter a short description with sale details.',
  'Confirm the description remains visible after typing.',
  'Confirm category choices are visible.',
  'Select at least one category.',
  'Confirm the selected category shows as selected or checked.',
  'If collectibles or special categories are selected, confirm the extra category detail field appears.',
  'Fill any displayed category detail field.',
  'Click Continue to move to the next screen.',
  'Confirm the next screen loads and the entered listing details are not lost.',
];

const residentialLocation = [
  'Confirm the address search field is visible.',
  'Click the address search field.',
  'Type the test address 874 Asheville St, Lindsay CA.',
  'Confirm address suggestions appear below the field.',
  'Click the correct address suggestion.',
  'Confirm the selected address appears in the address review area.',
  'Confirm the map preview updates to the selected address.',
  'Confirm a location pin appears on the map preview.',
  'If pin adjustment is available, drag or click the map to move the pin slightly.',
  'Confirm the pin stays at the adjusted position after release.',
  'Confirm city, state, and ZIP fields display the correct values.',
  'Click Continue to save location details.',
  'Confirm the flow advances without losing the address.',
];

const residentialSchedule = [
  'Confirm the date selection screen is visible.',
  'Select the first sale date.',
  'Confirm the selected start date is highlighted.',
  'Select the final sale date if a range is allowed.',
  'Confirm the selected end date is highlighted.',
  'Confirm the Open Time field is visible.',
  'Click Open Time and enter 08:00 AM or select it from the picker.',
  'Confirm the open time displays correctly.',
  'Confirm the Close Time field is visible.',
  'Click Close Time and enter 02:00 PM or select it from the picker.',
  'Confirm the close time displays correctly.',
  'Set Close Time earlier than Open Time.',
  'Click Continue.',
  'Confirm a validation message blocks the invalid time range.',
  'Set Close Time later than Open Time.',
  'Click Continue again.',
  'Confirm the schedule saves and the next screen opens.',
];

const residentialPhotos = [
  'Confirm the photo upload area is visible.',
  'Click the upload photo button or drop zone.',
  'Select a valid image file.',
  'Confirm an upload progress or loading state appears if applicable.',
  'Confirm the uploaded photo thumbnail appears.',
  'Upload an additional valid image if multiple photos are supported.',
  'Confirm both thumbnails remain visible.',
  'Remove one uploaded photo if a remove button is shown.',
  'Confirm the removed photo disappears from the preview.',
  'Upload the photo again.',
  'Click Continue.',
  'Confirm the photos remain attached on the next screen.',
];

const tierSelection = (tierName) => [
  'Confirm the tier selection or review screen is visible.',
  'Confirm Free, Featured, and Premium tier options are visible when applicable.',
  `Click the ${tierName} tier option.`,
  `Confirm the ${tierName} tier appears selected.`,
  `Confirm the ${tierName} tier price or free label is visible.`,
  `Confirm the ${tierName} tier benefit badges or description appear.`,
  'Click Continue or Review Listing.',
  'Confirm the listing preview screen opens.',
];

const previewSteps = [
  'Confirm the listing preview shows the title entered earlier.',
  'Confirm the listing preview shows the description entered earlier.',
  'Confirm the listing preview shows the selected categories.',
  'Confirm the listing preview shows the selected address.',
  'Confirm the listing preview shows the selected date range.',
  'Confirm the listing preview shows Open and Close visibility hours.',
  'Confirm uploaded photos appear in the preview.',
  'Confirm the selected tier badge appears in the preview.',
  'Click Back or Edit from preview if available.',
  'Confirm the previous step opens with previously entered values still saved.',
  'Return to preview.',
];

const paymentSteps = (tierName) => [
  `Click the button to continue with the ${tierName} listing payment.`,
  'Confirm the non-refundable or purchase acknowledgement appears if required.',
  'Check the required acknowledgement checkbox if shown.',
  'Click Continue to Checkout.',
  'Confirm a loading state appears while checkout is created.',
  'Confirm Stripe Checkout opens in the same tab or a new checkout screen.',
  'Confirm the checkout amount matches the selected tier.',
  'Confirm the listing title or Yardit purchase description appears in checkout.',
  'Enter valid Stripe test payment details.',
  'Click Pay or Submit Payment.',
  'Confirm the success return page or Yardit confirmation screen opens.',
  'Confirm no duplicate listing is created after returning from checkout.',
  'Open My Listings.',
  `Confirm the listing shows the ${tierName} tier badge.`,
  'Confirm payment status shows paid or activated.',
  'Open the listing detail page.',
  'Confirm the paid listing is visible with the correct tier styling.',
];

const receiptSteps = [
  'Open Profile or My Listings billing area.',
  'Find the payment history or receipt section.',
  'Click the receipt or billing detail for the test listing.',
  'Confirm the receipt shows listing title.',
  'Confirm the receipt shows paid amount.',
  'Confirm the receipt shows transaction date.',
  'Confirm the receipt shows payment status.',
  'Confirm Stripe transaction or checkout reference is displayed where expected.',
  'Return to the previous page.',
];

const mapVisibilitySteps = [
  'Open the Home map as a non-owner user or logged-out public viewer if allowed.',
  'Search near the listing location.',
  'Confirm the listing pin appears only when the current date and time match public visibility rules.',
  'Click the listing pin.',
  'Confirm the popup opens.',
  'Confirm the popup shows title, address, date, time, and tier badge.',
  'Open List View.',
  'Confirm the same listing appears in the list when it appears on the map.',
  'Change filters so the listing type is excluded.',
  'Confirm the listing disappears from map and list view.',
  'Re-enable the filter.',
  'Confirm the listing appears again.',
];

export const QA_FLOWS = [
  flow({
    category: 'Residential Listings',
    name: 'Free Listing Click-by-Click Flow',
    slug: 'residential-free-listing',
    relatedFiles: residentialBaseFiles,
    items: [
      ...residentialStart,
      ...residentialDetails,
      ...residentialLocation,
      ...residentialSchedule,
      ...residentialPhotos,
      ...tierSelection('Free'),
      ...previewSteps,
      'Click Publish Free Listing.',
      'Confirm a saving or publishing state appears.',
      'Confirm the success message appears.',
      'Click View Listing or open My Listings.',
      'Confirm the new free listing appears in My Listings.',
      'Confirm the card shows Free badge.',
      'Confirm the card shows Open and Close visibility hours.',
      'Confirm no checkout or payment screen was required.',
      ...mapVisibilitySteps,
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Featured Listing Payment Flow',
    slug: 'residential-featured-listing',
    relatedFiles: residentialBaseFiles.concat(paymentBaseFiles),
    items: [
      ...residentialStart,
      ...residentialDetails,
      ...residentialLocation,
      ...residentialSchedule,
      ...residentialPhotos,
      ...tierSelection('Featured'),
      ...previewSteps,
      ...paymentSteps('Featured'),
      ...receiptSteps,
      ...mapVisibilitySteps,
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Premium Listing Payment Flow',
    slug: 'residential-premium-listing',
    relatedFiles: residentialBaseFiles.concat(paymentBaseFiles),
    items: [
      ...residentialStart,
      ...residentialDetails,
      ...residentialLocation,
      ...residentialSchedule,
      'Confirm Premium early visibility controls appear after choosing Premium.',
      'Select one early visibility day if available.',
      'Confirm the selected early visibility day appears highlighted.',
      ...residentialPhotos,
      ...tierSelection('Premium'),
      ...previewSteps,
      'Confirm the preview displays Premium Coming Soon or early visibility messaging when future visibility applies.',
      ...paymentSteps('Premium'),
      ...receiptSteps,
      ...mapVisibilitySteps,
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Premium Coming Soon Visibility Flow',
    slug: 'residential-premium-coming-soon',
    relatedFiles: residentialBaseFiles,
    items: [
      'Create or locate a paid Premium listing with future active sale dates and early visibility enabled.',
      'Open Home map before the active sale date but during the early visibility window.',
      'Confirm the Premium listing appears as Coming Soon instead of Active.',
      'Confirm the listing pin uses Premium styling.',
      'Click the Premium pin.',
      'Confirm the popup opens.',
      'Confirm the popup shows a Coming Soon badge.',
      'Confirm the popup shows the future active sale date.',
      'Confirm the popup shows Open and Close visibility hours.',
      'Open List View.',
      'Confirm the same listing appears with Coming Soon messaging.',
      'Open Listing Detail.',
      'Confirm the detail page shows Premium badge and Coming Soon state.',
      'Confirm Save, Share, and Report actions are visible to eligible users.',
      'Advance testing to the active date/time or use a test listing already active.',
      'Refresh Home map.',
      'Confirm the listing state changes from Coming Soon to Active/Open.',
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Open and Close Hours Flow',
    slug: 'residential-open-close-hours',
    relatedFiles: residentialBaseFiles,
    items: [
      ...residentialSchedule,
      'Save a listing with Open Time 08:00 AM and Close Time 02:00 PM.',
      'Open My Listings.',
      'Confirm the listing card displays Open 8:00 AM and Close 2:00 PM or equivalent formatted times.',
      'Open Listing Detail.',
      'Confirm the detail page displays the same Open and Close times.',
      'Open Home map during the public open window.',
      'Confirm the listing appears on the public map.',
      'Open Home map outside the public open window.',
      'Confirm the listing does not appear as publicly open.',
      'Open owner preview or My Listings as the owner.',
      'Confirm the owner can still see the listing record even when public visibility is closed.',
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Listing Edit Flow',
    slug: 'residential-listing-edit',
    relatedFiles: residentialBaseFiles,
    items: [
      'Log in as the owner of an existing residential listing.',
      'Open My Listings.',
      'Find the target listing card.',
      'Confirm the Edit button is visible on the owner card.',
      'Click Edit.',
      'Confirm the edit modal or edit page opens.',
      'Confirm title field shows the current title.',
      'Change the title.',
      'Confirm description field shows the current description.',
      'Change the description.',
      'Confirm category controls show the current selections.',
      'Change one category.',
      'Confirm photo controls are visible.',
      'Add or remove a photo.',
      'Confirm Open and Close visibility hour controls are visible.',
      'Change Open Time and Close Time.',
      'Click Save.',
      'Confirm a saving state appears.',
      'Confirm the edit modal closes or a success message appears.',
      'Confirm the My Listings card shows the updated title and hours.',
      'Open Listing Detail.',
      'Confirm all edited values appear correctly.',
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Listing Upgrade Flow',
    slug: 'residential-listing-upgrade',
    relatedFiles: residentialBaseFiles.concat(paymentBaseFiles),
    items: [
      'Log in as the owner of a Free residential listing.',
      'Open My Listings.',
      'Find the Free listing card.',
      'Confirm the Upgrade button is visible.',
      'Click Upgrade.',
      'Confirm the upgrade modal opens.',
      'Confirm Featured and Premium upgrade options appear.',
      'Click Featured upgrade option.',
      'Confirm Featured price and benefits appear.',
      'Click Continue to Checkout.',
      'Confirm Stripe Checkout opens.',
      'Cancel checkout before paying.',
      'Return to Yardit.',
      'Confirm the listing is still Free and does not show Featured benefits.',
      'Click Upgrade again.',
      'Choose Featured or Premium.',
      'Complete payment successfully.',
      'Return to Yardit.',
      'Confirm the listing card now shows the upgraded tier badge.',
      'Open Home map.',
      'Confirm the map pin reflects the upgraded tier.',
      'Open receipt or billing details.',
      'Confirm the upgrade transaction appears.',
    ],
  }),
  flow({
    category: 'Residential Listings',
    name: 'Expiration and Relist Flow',
    slug: 'residential-expiration-relist',
    relatedFiles: residentialBaseFiles,
    items: [
      'Create or locate a residential listing with an end date/time in the past.',
      'Open Home map as a public viewer.',
      'Confirm the expired listing does not appear on the public map.',
      'Open List View.',
      'Confirm the expired listing does not appear in public list results.',
      'Log in as the listing owner.',
      'Open My Listings.',
      'Click the Expired tab.',
      'Confirm the expired listing appears in owner history.',
      'Confirm the expired card displays an Expired badge or status.',
      'Confirm the Relist button is visible.',
      'Click Relist.',
      'Confirm the relist modal or relist flow opens.',
      'Select a new future date.',
      'Confirm Open and Close time fields are visible.',
      'Enter valid Open and Close times.',
      'Click Save or Publish Relist.',
      'Confirm success message appears.',
      'Confirm the listing moves from Expired to Active or Scheduled tab.',
      'Open Home map during its public visibility window.',
      'Confirm the relisted listing appears publicly again.',
    ],
  }),
  flow({
    category: 'Neighborhood Sales',
    name: 'Create Neighborhood Sale and Organizer Setup Flow',
    slug: 'neighborhood-create-organizer-setup',
    relatedFiles: neighborhoodBaseFiles,
    items: [
      'Open Yardit and log in as the neighborhood sale organizer.',
      'Click Post Sale.',
      'Confirm the listing type selection screen opens.',
      'Click Neighborhood Sale.',
      'Confirm the neighborhood sale intro or setup screen opens.',
      'Confirm organizer explanation text is visible.',
      'Click Start or Continue.',
      'Confirm organizer participation options appear.',
      'Select participating organizer mode.',
      'Confirm organizer listing fields appear.',
      'Enter neighborhood sale title.',
      'Enter neighborhood sale description.',
      'Confirm host address field is visible.',
      'Enter the host address.',
      'Confirm address suggestions appear.',
      'Select the correct host address suggestion.',
      'Confirm the host map preview centers on the address.',
      'Confirm radius preview appears if available.',
      'Select sale dates.',
      'Enter Open Time and Close Time.',
      'Click Continue.',
      'Confirm billing setup or review screen opens.',
      'Confirm base neighborhood sale price is displayed.',
      'Confirm per-home pricing breakdown is displayed.',
      'Click Create or Continue to Payment.',
      'Complete required payment setup or checkout.',
      'Confirm the organizer dashboard/panel opens after setup.',
      'Confirm the organizer listing shows a bold HOST badge in My Listings.',
      'Confirm Upgrade button is not shown on the neighborhood sale host listing.',
    ],
  }),
  flow({
    category: 'Neighborhood Sales',
    name: 'Radius Validation and Ask To Join Flow',
    slug: 'neighborhood-radius-ask-to-join',
    relatedFiles: neighborhoodBaseFiles,
    items: [
      'Open a public neighborhood sale detail page as a different logged-in user.',
      'Confirm the neighborhood title is visible.',
      'Confirm organizer information is visible.',
      'Confirm participant count is visible.',
      'Confirm Ask To Join or Join button is visible.',
      'Click Ask To Join.',
      'Confirm the join dialog opens.',
      'Confirm address field is visible.',
      'Enter an address outside the allowed radius.',
      'Click Validate or Continue.',
      'Confirm a radius validation error appears.',
      'Confirm the user cannot submit the join request with the invalid address.',
      'Replace the address with a valid address within the neighborhood radius.',
      'Click Validate or Continue.',
      'Confirm the validation success message appears.',
      'Confirm participant listing fields appear.',
      'Enter participant sale title.',
      'Enter participant sale description.',
      'Select participant categories.',
      'Confirm the sale dates and hours match or align with the neighborhood sale rules.',
      'Click Submit Join Request.',
      'Confirm a pending request confirmation appears.',
      'Open My Listings as the participant.',
      'Confirm the participant listing shows Pending approval status.',
    ],
  }),
  flow({
    category: 'Neighborhood Sales',
    name: 'Approve, Deny, and Remove Participant Flow',
    slug: 'neighborhood-approval-removal',
    relatedFiles: neighborhoodBaseFiles.concat(notificationBaseFiles),
    items: [
      'Log in as the neighborhood sale organizer.',
      'Open My Listings.',
      'Open the organizer neighborhood sale card or detail page.',
      'Confirm the Neighborhood Sale Panel is visible.',
      'Confirm pending join request appears in the participant/request list.',
      'Click Approve on the pending request.',
      'Confirm an approval confirmation prompt appears if used.',
      'Confirm the participant status changes to Approved.',
      'Confirm the participant appears in the approved homes list.',
      'Confirm the home count increases by one.',
      'Confirm billing summary updates if per-home charges apply.',
      'Log in as the participant.',
      'Confirm notification bell shows a new notification or participant status updates.',
      'Open My Listings.',
      'Confirm participant listing now shows Approved status.',
      'Create or locate another pending join request.',
      'Log in as organizer and open the request list.',
      'Click Deny on the pending request.',
      'Enter denial reason if prompted.',
      'Confirm denied status appears.',
      'Log in as denied participant.',
      'Confirm the participant sees Denied status or notification.',
      'Return as organizer to an approved participant.',
      'Click Remove Participant.',
      'Confirm removal confirmation modal opens.',
      'Enter removal reason if prompted.',
      'Confirm the participant is removed from approved homes.',
      'Confirm home count decreases by one.',
      'Confirm public map no longer shows the removed participant as part of the sale.',
    ],
  }),
  flow({
    category: 'Neighborhood Sales',
    name: 'Billing, Activation, Coming Soon, Public View, Organizer View Flow',
    slug: 'neighborhood-billing-activation-public-organizer',
    relatedFiles: neighborhoodBaseFiles.concat(paymentBaseFiles),
    items: [
      'Open the organizer neighborhood sale detail page.',
      'Confirm billing total is visible without expanding details.',
      'Expand Billing details.',
      'Confirm transaction history appears inside the Billing section.',
      'Confirm base price is listed.',
      'Confirm per-home price is listed.',
      'Confirm additional due amount is shown when participant count changes.',
      'Click Pay Additional Due if shown.',
      'Confirm checkout opens for the adjustment amount.',
      'Complete or cancel checkout according to the test case.',
      'Return to organizer view.',
      'Confirm payment status updates correctly.',
      'Confirm the neighborhood sale status changes to ready, active, collecting, or payment pending as expected.',
      'Open public Home map before active date if coming soon applies.',
      'Confirm neighborhood sale appears with Coming Soon badge when eligible.',
      'Open public Home map during active date/time.',
      'Confirm neighborhood sale appears as Active/Open.',
      'Click the neighborhood sale pin.',
      'Confirm popup shows organizer, date, hours, participant count, and join/share actions.',
      'Open Listing Detail as a public viewer.',
      'Confirm public view hides organizer-only approval controls.',
      'Open Listing Detail as organizer.',
      'Confirm organizer-only controls are visible.',
      'Confirm organizer can view participant requests, approved homes, billing, and status.',
    ],
  }),
  flow({
    category: 'Map / Home',
    name: 'Initial Load, Search, Filters, Location Permission Flow',
    slug: 'map-home-load-search-filters-location',
    relatedFiles: mapBaseFiles,
    items: [
      'Open Yardit Home.',
      'Confirm map container loads.',
      'Confirm no full-page error appears.',
      'Confirm current location button appears.',
      'Confirm search field appears.',
      'Confirm filter button appears.',
      'Confirm list/map toggle appears if available.',
      'Click the search field.',
      'Type Lindsay CA.',
      'Confirm search suggestions or search result behavior appears.',
      'Submit the search.',
      'Confirm the map moves to the searched area.',
      'Click current location button.',
      'Confirm browser location permission prompt appears when permission has not been granted.',
      'Click Allow.',
      'Confirm the map centers near the current location.',
      'Repeat location test and click Block or Deny.',
      'Confirm Yardit shows a helpful permission or location unavailable message.',
      'Click Filters.',
      'Confirm filter modal opens.',
      'Confirm listing type filters appear.',
      'Turn off Residential listings.',
      'Confirm residential pins disappear.',
      'Turn Residential listings back on.',
      'Confirm residential pins reappear.',
      'Apply date or status filters if visible.',
      'Confirm map and list results update together.',
      'Click Reset Filters if visible.',
      'Confirm filters return to default and results refresh.',
    ],
  }),
  flow({
    category: 'Map / Home',
    name: 'Zoom, Clustering, Pin Selection, Popup Actions Flow',
    slug: 'map-home-zoom-cluster-pin-popup',
    relatedFiles: mapBaseFiles.concat(detailBaseFiles),
    items: [
      'Open Home map near an area with multiple listings.',
      'Zoom out until nearby listings cluster together.',
      'Confirm cluster marker appears with a count.',
      'Click the cluster marker.',
      'Confirm the map zooms in or expands the cluster.',
      'Zoom in until individual pins appear.',
      'Confirm each visible pin uses the correct icon or tier styling.',
      'Click a residential pin.',
      'Confirm popup opens.',
      'Confirm popup shows listing title.',
      'Confirm popup shows address or location label.',
      'Confirm popup shows date and Open/Close time.',
      'Confirm popup shows tier/status badge.',
      'Click View Details from popup.',
      'Confirm Listing Detail page or card opens.',
      'Return to Home map.',
      'Click Add Stop on a popup or listing card if visible.',
      'Confirm the stop is added to the route builder or hunt route.',
      'Click Save or Bookmark.',
      'Confirm bookmark state changes to saved.',
      'Click Report.',
      'Confirm report modal opens.',
      'Close report modal.',
      'Open route builder.',
      'Confirm selected stop appears in route list.',
      'Remove the stop.',
      'Confirm route list updates immediately.',
    ],
  }),
  flow({
    category: 'Map / Home',
    name: 'Coming Soon Visibility and Owner Preview Toggle Flow',
    slug: 'map-coming-soon-owner-preview',
    relatedFiles: mapBaseFiles.concat(residentialBaseFiles),
    items: [
      'Create or locate a future scheduled listing owned by the test user.',
      'Open Home map as a public viewer.',
      'Confirm the listing appears only if its public visibility rules allow Coming Soon display.',
      'Confirm the listing does not appear if it is outside all public visibility windows.',
      'Log in as the owner.',
      'Open Home map.',
      'Find the owner preview toggle if available.',
      'Turn owner preview on.',
      'Confirm owner-only preview listings become visible to the owner.',
      'Confirm owner preview listings show a clear owner/preview badge or state.',
      'Turn owner preview off.',
      'Confirm owner-only preview listings hide again from normal public map view.',
      'Open List View with owner preview on.',
      'Confirm owner preview results match map preview results.',
      'Open List View with owner preview off.',
      'Confirm public list results do not include private owner-only listings.',
    ],
  }),
  flow({
    category: 'My Listings',
    name: 'Tabs, Search, Filters, Card Actions Flow',
    slug: 'my-listings-tabs-search-filters-actions',
    relatedFiles: myListingsBaseFiles,
    items: [
      'Log in as a user with active, scheduled, expired, hidden, and canceled test listings.',
      'Open the account menu.',
      'Click My Listings.',
      'Confirm My Listings page loads.',
      'Confirm tabs are visible.',
      'Click Active tab.',
      'Confirm active listings appear.',
      'Confirm active cards show status badge, date range, Open/Close hours, and action buttons.',
      'Click Scheduled tab.',
      'Confirm scheduled listings appear with scheduled or coming soon badge.',
      'Click Expired tab.',
      'Confirm expired listings appear with expired badge.',
      'Click Hidden tab if visible.',
      'Confirm hidden listings appear with hidden badge.',
      'Click Canceled tab if visible.',
      'Confirm canceled listings appear with canceled badge.',
      'Click search field.',
      'Type part of a listing title.',
      'Confirm matching listing cards remain visible.',
      'Confirm non-matching listing cards are hidden.',
      'Clear search field.',
      'Confirm all listings for the active tab return.',
      'Open filter controls if available.',
      'Apply a tier or listing type filter.',
      'Confirm cards update to match the filter.',
      'Reset filters.',
      'Confirm cards return.',
    ],
  }),
  flow({
    category: 'My Listings',
    name: 'View, Edit, Relist, Upgrade, Receipt, Billing Flow',
    slug: 'my-listings-card-actions-billing',
    relatedFiles: myListingsBaseFiles.concat(paymentBaseFiles),
    items: [
      'Open My Listings as a listing owner.',
      'Find an active residential listing card.',
      'Click View Listing.',
      'Confirm Listing Detail opens for the correct listing.',
      'Return to My Listings.',
      'Click Edit.',
      'Confirm edit modal opens.',
      'Close edit modal without saving.',
      'Confirm listing card remains unchanged.',
      'Click Upgrade on a Free listing.',
      'Confirm upgrade modal opens.',
      'Close upgrade modal.',
      'Confirm listing tier remains unchanged.',
      'Open an expired listing card.',
      'Click Relist.',
      'Confirm relist controls open.',
      'Close relist controls without saving.',
      'Confirm expired status remains unchanged.',
      'Find a paid listing card.',
      'Click Receipt or Billing if visible.',
      'Confirm billing details open.',
      'Confirm billing total appears.',
      'Confirm transaction rows show date, amount, status, and listing reference.',
      'Close billing details.',
      'Confirm user returns to My Listings.',
    ],
  }),
  flow({
    category: 'Listing Detail',
    name: 'All Sections, Photos, Times, Dates, Badges, Actions Flow',
    slug: 'listing-detail-all-sections-actions',
    relatedFiles: detailBaseFiles,
    items: [
      'Open a residential Listing Detail page.',
      'Confirm page title or listing title is visible.',
      'Confirm photo gallery section is visible.',
      'Click the first photo.',
      'Confirm photo opens or enlarges if gallery supports it.',
      'Navigate to the next photo if multiple photos exist.',
      'Confirm next photo appears.',
      'Close photo viewer if opened.',
      'Confirm description section is visible.',
      'Confirm categories or item badges are visible.',
      'Confirm tier badge is visible.',
      'Confirm status badge is visible.',
      'Confirm date range is visible.',
      'Confirm Open/Close hours are visible.',
      'Confirm address or location section is visible.',
      'Click Share.',
      'Confirm share action opens native share or copies link.',
      'Click Bookmark or Save.',
      'Confirm saved state changes.',
      'Click Bookmark or Save again.',
      'Confirm saved state is removed.',
      'Click Report.',
      'Confirm report modal opens.',
      'Close report modal.',
      'Click Add Stop or route action if visible.',
      'Confirm route action updates the route builder or hunt state.',
    ],
  }),
  flow({
    category: 'Profile',
    name: 'Registration, Login, Logout, Forgot Password, Name and Terms Flow',
    slug: 'profile-auth-name-terms',
    relatedFiles: profileBaseFiles,
    items: [
      'Open Yardit while logged out.',
      'Click Log In / Sign Up.',
      'Confirm authentication screen opens.',
      'Choose sign up.',
      'Enter a valid email address.',
      'Enter a valid password if password field is shown.',
      'Submit registration.',
      'Confirm any required verification or account setup message appears.',
      'Complete verification steps available to the tester.',
      'Return to Yardit.',
      'Confirm name collection modal appears if the account has no name.',
      'Confirm first name or full name field is visible.',
      'Leave required name field blank.',
      'Click Save or Continue.',
      'Confirm validation message appears.',
      'Enter tester name.',
      'Confirm terms acceptance checkbox or terms prompt appears if required.',
      'Attempt to continue without accepting terms.',
      'Confirm validation or blocker appears.',
      'Accept terms.',
      'Click Save or Continue.',
      'Confirm modal closes and app is usable.',
      'Open account menu.',
      'Click Logout.',
      'Confirm user returns to logged-out or Coming Soon state.',
      'Click Log In / Sign Up again.',
      'Click Forgot Password if available.',
      'Confirm forgot password screen opens.',
      'Enter email address and submit.',
      'Confirm reset confirmation message appears.',
    ],
  }),
  flow({
    category: 'Profile',
    name: 'Profile Completion, Address, Phone, Email, Settings Flow',
    slug: 'profile-completion-address-settings',
    relatedFiles: profileBaseFiles,
    items: [
      'Log in as a test user.',
      'Open account menu.',
      'Click My Profile.',
      'Confirm Profile page loads.',
      'Confirm user name appears.',
      'Confirm email address appears and matches the logged-in account.',
      'Confirm profile completion or setup area appears if profile is incomplete.',
      'Confirm primary address section is visible.',
      'Click Add Address or Edit Address.',
      'Confirm address entry modal or section opens.',
      'Leave required address field blank.',
      'Click Save.',
      'Confirm validation message appears.',
      'Enter street address.',
      'Enter city.',
      'Enter state.',
      'Enter ZIP code.',
      'Click Confirm Address or Save.',
      'Confirm address confirmation screen or map review appears.',
      'Confirm displayed address is correct.',
      'Click Confirm.',
      'Confirm address verification status changes to confirmed or verified.',
      'Click reverification or edit address if available.',
      'Change the address.',
      'Confirm reverification is required before listing creation proceeds.',
      'Confirm phone number is not required for core residential posting.',
      'Open Settings.',
      'Confirm settings page loads.',
      'Change a setting if available.',
      'Click Save.',
      'Confirm setting persists after refresh.',
    ],
  }),
  flow({
    category: 'Notifications',
    name: 'Bell, Popup, View All, Read, Unread, Navigation, Auto Close Flow',
    slug: 'notifications-bell-popup-read-navigation',
    relatedFiles: notificationBaseFiles,
    items: [
      'Log in as a user with at least one notification.',
      'Confirm notification bell appears in the header.',
      'Confirm unread count badge appears when unread notifications exist.',
      'Click the bell icon.',
      'Confirm notification popup opens.',
      'Confirm unread notification rows are visually distinct.',
      'Click one unread notification.',
      'Confirm it marks as read or navigates to the related page.',
      'Return to the previous page if navigation occurred.',
      'Click the bell again.',
      'Confirm the selected notification no longer appears unread.',
      'Click View All.',
      'Confirm Notifications page opens.',
      'Confirm read and unread notifications are listed.',
      'Click a notification with a related listing or ticket.',
      'Confirm it navigates to the related page.',
      'Return to Notifications.',
      'Open notification popup again.',
      'Click outside the popup.',
      'Confirm popup auto closes.',
    ],
  }),
  flow({
    category: 'Support',
    name: 'Contact Support, Categories, Routing, Ticket Creation and History Flow',
    slug: 'support-contact-routing-ticket-history',
    relatedFiles: supportBaseFiles,
    items: [
      'Open Contact Support page.',
      'Confirm support form loads.',
      'Confirm category or support area options appear.',
      'Select Residential support category.',
      'Confirm routing or category selection remains visible.',
      'Leave required fields blank.',
      'Click Submit.',
      'Confirm validation messages appear for required fields.',
      'Enter name if required.',
      'Enter email address.',
      'Confirm phone number is not required for submission.',
      'Enter issue description.',
      'Upload a screenshot or photo if upload is available.',
      'Confirm uploaded file preview appears.',
      'Click Submit.',
      'Confirm loading or submitting state appears.',
      'Confirm success message appears.',
      'Confirm ticket number appears.',
      'Open My Support Tickets.',
      'Confirm the new ticket appears in ticket history.',
      'Confirm ticket status appears.',
      'Open the ticket detail.',
      'Confirm description and uploaded photo are visible.',
      'Log in as admin.',
      'Open support queue.',
      'Confirm the ticket appears in the correct residential queue.',
    ],
  }),
  flow({
    category: 'Report Flow',
    name: 'Report Listing, Report User, Validation, Submission, Admin Review Flow',
    slug: 'report-listing-user-admin-review',
    relatedFiles: detailBaseFiles.concat(supportBaseFiles),
    items: [
      'Open a public listing detail page as a logged-in user.',
      'Click Report.',
      'Confirm report modal opens.',
      'Confirm report reason choices appear.',
      'Click Submit without choosing a reason.',
      'Confirm validation message appears.',
      'Select a report reason.',
      'Confirm details text area appears if required.',
      'Enter report details.',
      'Upload optional screenshot if available.',
      'Confirm screenshot preview appears.',
      'Click Submit Report.',
      'Confirm submitting state appears.',
      'Confirm success message appears.',
      'Confirm report modal closes or shows completion state.',
      'Open the same listing as owner if applicable.',
      'Confirm owner does not see private reporter details publicly.',
      'Log in as admin.',
      'Open Reports or Support Queue.',
      'Confirm the report appears in admin review.',
      'Open the report record.',
      'Confirm listing reference is visible.',
      'Confirm reporter/user context is visible to admin.',
      'Change report status or listing status as an admin action.',
      'Confirm status change saves.',
      'Open public Home map.',
      'Confirm hidden or suspended listing no longer appears publicly if that action was selected.',
    ],
  }),
  flow({
    category: 'Payments',
    name: 'Checkout, Promo Codes, Success, Cancel, Retry, Receipts, Transactions, Billing Views Flow',
    slug: 'payments-checkout-promo-receipt-transactions',
    relatedFiles: paymentBaseFiles,
    items: [
      'Start a paid Featured or Premium residential listing checkout.',
      'Confirm checkout review screen shows selected tier.',
      'Confirm checkout review screen shows amount due.',
      'Click promo code field.',
      'Enter an invalid promo code.',
      'Click Apply.',
      'Confirm invalid promo validation message appears.',
      'Enter a valid percentage promo code if available.',
      'Click Apply.',
      'Confirm discount amount appears.',
      'Confirm final amount updates correctly.',
      'Remove promo code if removal is available.',
      'Confirm total returns to original amount.',
      'Click Continue to Checkout.',
      'Confirm Stripe Checkout opens.',
      'Cancel checkout.',
      'Confirm Yardit returns to cancel or unpaid state.',
      'Confirm paid benefits are not granted after cancel.',
      'Click Retry Payment or restart checkout.',
      'Confirm a new valid checkout opens.',
      'Complete payment successfully.',
      'Confirm Yardit success screen appears.',
      'Open My Listings.',
      'Confirm listing payment status is paid.',
      'Open billing or receipt view.',
      'Confirm receipt shows amount, status, date, listing, and transaction reference.',
      'Log in as admin.',
      'Open payment transactions or billing view.',
      'Confirm the payment transaction appears with matching listing ID and user email.',
    ],
  }),
  flow({
    category: 'Admin',
    name: 'Dashboard, Listings, Users, Support, Reports, Billing, Transactions Flow',
    slug: 'admin-dashboard-core-management',
    relatedFiles: adminBaseFiles.concat(paymentBaseFiles, supportBaseFiles),
    items: [
      'Log in as an authorized admin user.',
      'Open Admin Login or Admin Lite.',
      'Enter Employee ID.',
      'Enter PIN.',
      'Click Login.',
      'Confirm admin dashboard opens.',
      'Confirm dashboard summary cards are visible.',
      'Click Residential Listings section.',
      'Confirm residential listing table opens.',
      'Use search field to search by listing title.',
      'Confirm matching listings appear.',
      'Apply a status filter.',
      'Confirm listings update to match the filter.',
      'Open a listing detail row.',
      'Confirm listing detail panel shows owner, title, dates, times, status, and payment state.',
      'Change listing status to hidden or under review in a safe test record.',
      'Click Save.',
      'Confirm status change saves.',
      'Open Home map as public viewer.',
      'Confirm hidden or under review listing is no longer public.',
      'Return to Admin.',
      'Open Neighborhood Sales section if available.',
      'Confirm organizer, participant count, billing status, and activation status are visible.',
      'Open Users section.',
      'Search for a user by email.',
      'Confirm user detail opens.',
      'Open Support Queue.',
      'Confirm support tickets appear.',
      'Open Reports queue if separate.',
      'Confirm reports appear.',
      'Open Billing or Transactions section.',
      'Confirm payment transactions show user, amount, status, and related listing.',
    ],
  }),
  flow({
    category: 'Admin',
    name: 'Assisted Listings and QR Code Review-Only QA Flow',
    slug: 'admin-assisted-listings-qr-review-only',
    relatedFiles: [
      'components/admin/assisted/AdminAssistedListingsTab',
      'components/admin/assisted/AdminAssistedListingHistory',
      'components/admin/assisted/AdminQRViewModal',
      'components/admin/assisted/AssistedListingQRPanel',
      'pages/AssistedListingApproval',
    ],
    items: [
      'Open Admin as an authorized admin user.',
      'Open Assisted Listings section.',
      'Confirm assisted listing records load.',
      'Confirm each record shows seller approval status.',
      'Confirm each record shows listing number if available.',
      'Open an assisted listing record in view mode.',
      'Confirm QR code area is visible only where the existing locked workflow allows it.',
      'Confirm QR code image or QR status appears without changing QR generation logic.',
      'Confirm approval URL or QR label appears if already provided by the system.',
      'Close the QR view modal.',
      'Confirm no QR regeneration or approval action was triggered during this review-only test.',
      'Confirm assisted listing history remains unchanged after simply viewing QR information.',
    ],
  }),
  flow({
    category: 'Approval and Freeze',
    name: 'Approve Flow',
    slug: 'qa-approve-flow',
    relatedFiles: ['components/checklist/LaunchChecklistContent', 'components/checklist/qaFlowData.js', 'lib/launchChecklistStorage.js'],
    items: [
      'Open the Yardit QA Checklist System.',
      'Select a QA flow with all checklist items tested.',
      'Confirm every item has either Pass or Fail selected.',
      'Confirm all failed items include notes explaining the issue.',
      'Confirm Tested By is filled for each completed item.',
      'Confirm Tested Date is filled for each completed item.',
      'Confirm screenshot notes or screenshot references are added where useful.',
      'Review the Related Files list for the selected flow.',
      'Confirm the flow version is visible.',
      'Enter Approved By name.',
      'Click Approve Flow.',
      'Confirm approval date is saved automatically.',
      'Confirm Flow Name is saved.',
      'Confirm Version is saved.',
      'Confirm Approved By is saved.',
      'Confirm Approved Date is saved.',
      'Confirm Related Files are saved.',
      'Refresh the page.',
      'Confirm approval information still appears.',
    ],
  }),
  flow({
    category: 'Approval and Freeze',
    name: 'Freeze Flow and Needs Retest Flow',
    slug: 'qa-freeze-needs-retest-flow',
    relatedFiles: ['components/checklist/LaunchChecklistContent', 'components/checklist/qaFlowData.js', 'lib/launchChecklistStorage.js'],
    items: [
      'Open the Yardit QA Checklist System.',
      'Approve a completed flow first.',
      'Confirm approval information appears in the flow header.',
      'Click Freeze Flow.',
      'Confirm freeze confirmation appears or freeze state saves.',
      'Confirm frozen flow shows Frozen status.',
      'Confirm related files remain visible on the frozen flow.',
      'Confirm the frozen flow can still be reviewed without changing source code.',
      'Update the QA flow version or related file list in a future app change.',
      'Reopen the QA Checklist System after that change.',
      'Confirm the flow is marked Needs Retest when the saved approved version no longer matches the current flow version.',
      'Confirm Changed File or changed version information is shown.',
      'Confirm Potentially Affected Flow shows the flow name.',
      'Retest the changed flow items.',
      'Approve the flow again after retesting.',
      'Confirm Needs Retest status clears after reapproval.',
    ],
  }),
];

export const QA_CATEGORIES = [...new Set(QA_FLOWS.map(flow => flow.category))];