const files = {
  residential: ['pages/CreateListing', 'components/create/CreateListingResidential', 'components/create/StepOne', 'components/create/StepTwo', 'components/create/StepThree', 'components/create/OpenHoursFields', 'components/payment/ResidentialPaymentStep', 'components/shared/CharacterCounter', 'pages/MyListings', 'components/listing/MyListingCard', 'components/listing/EditListingDialog', 'components/listing/ListingUpgradeDialog', 'pages/ListingDetail', 'pages/Home', 'components/home/ListView', 'lib/residentialDescriptionLimits.js', 'lib/listingVisibility.js', 'lib/listViewPipeline.js', 'functions/saveResidentialListing'],
  neighborhood: ['pages/CreateListing', 'components/create/CreateListingNeighborhood', 'components/create/StepTwo', 'components/create/NeighborhoodSaleIntroModal', 'components/create/NeighborhoodJoinDialogs', 'components/shared/CharacterCounter', 'components/listing/NeighborhoodSalePanel', 'pages/JoinNeighborhoodSale', 'pages/MyListings', 'pages/ListingDetail', 'functions/saveResidentialListing', 'functions/respondToJoinRequest', 'functions/createNeighborhoodSaleSetup', 'functions/neighborhoodSaleSetupCheckout', 'functions/cancelNeighborhoodSale', 'lib/residentialDescriptionLimits.js', 'lib/neighborhoodSalePricing.js', 'lib/neighborhoodSaleState.js'],
  map: ['pages/Home', 'components/home/ListView', 'components/home/ListFilterModal', 'components/map/ClusterGroup', 'components/map/QuickMapFilters', 'components/map/RouteBuilder', 'components/map/CheckInButton', 'components/map/HiddenListingsOverlay', 'lib/listingVisibility.js', 'lib/listViewPipeline.js'],
  myListings: ['pages/MyListings', 'components/listing/MyListingCard', 'components/listing/MyListingActions', 'components/listing/EditListingDialog', 'components/listing/ListingUpgradeDialog', 'components/billing/ResidentialBillingList', 'lib/myListingsHelpers.js'],
  detail: ['pages/ListingDetail', 'components/listing/ListingPhotoGallery', 'components/listing/ListingShareButton', 'components/listing/SaveListingButton', 'components/listing/listingDisplay', 'components/listing/listingDetailContent', 'components/ReportModal'],
  profile: ['pages/Profile', 'pages/AccountOptions', 'pages/Settings', 'components/profile/AccountSetupModal', 'components/profile/VerifiedAddressRequiredModal', 'components/profile/UserInfoSection', 'components/create/PrimaryAddressVerificationModal', 'components/create/PrimaryAddressVerificationGate', 'lib/AuthContext.jsx', 'hooks/useGuestGuard.js'],
  notifications: ['components/notifications/NotificationBell', 'components/notifications/NotificationList', 'pages/Notifications'],
  support: ['pages/ContactSupport', 'pages/MySupportTickets', 'components/admin/SupportTicketQueue', 'pages/CaseManagement', 'functions/createCaseFromReport'],
  payments: ['components/payment/ResidentialPaymentStep', 'components/payment/PromoCodeInput', 'components/profile/PaymentHistory', 'components/billing/ResidentialBillingList', 'components/billing/ResidentialReceiptDetail', 'functions/createResidentialListingCheckout', 'functions/createListingUpgradeCheckout', 'functions/residentialStripeCheckout', 'functions/saveResidentialListing', 'functions/stripeWebhook', 'functions/validateResidentialPromoCode', 'functions/linkPaymentTransactionsForListing'],
  residentialPromos: ['entities/Listing.json', 'entities/ResidentialPromoCode.json', 'entities/ResidentialPromoRedemption.json', 'components/admin/residential-promos/ResidentialPromoCodeModal', 'components/admin/residential-promos/ResidentialPromoCodesTab', 'components/payment/PromoCodeInput', 'functions/validateResidentialPromoCode', 'functions/residentialStripeCheckout', 'pages/CreateListing', 'lib/listingVisibility.js'],
  residentialEvents: ['pages/CreateListing', 'components/create/CreateListingEvent', 'components/create/event/EventDetailsStep', 'components/create/event/EventScheduleStep', 'components/create/event/EventTierStep', 'components/shared/CharacterCounter', 'components/payment/ResidentialPaymentStep', 'components/listing/EventFlyerDisplay', 'components/map/eventMarkerIcons', 'lib/residentialDescriptionLimits.js', 'lib/eventListingConfig.js', 'lib/listingVisibility.js', 'functions/saveResidentialListing', 'functions/residentialStripeCheckout'],
  paymentAudit: ['pages/PaymentAudit', 'components/admin/payments/PaymentAuditDashboard', 'components/admin/payments/PaymentAuditFilters', 'components/admin/payments/PaymentAuditIssuesTable', 'components/admin/payments/PaymentAuditSummaryCards', 'functions/paymentAuditScan', 'entities/PaymentAuditReview.json', 'entities/PaymentTransaction.json'],
  admin: ['pages/AdminLite', 'components/admin/AdminLiteDashboard', 'components/admin/ListingManagement', 'components/admin/UserManagement', 'components/admin/SupportTicketQueue', 'components/admin/payments/PaymentAuditDashboard', 'components/admin/AdminLogsTab', 'components/admin/system-health/SystemHealthDashboard', 'functions/paymentAuditScan', 'functions/runSystemHealthScan'],
  qa: ['components/checklist/LaunchChecklistContent', 'components/checklist/qaFlowData.js', 'lib/launchChecklistStorage.js']
};

const unique = (items) => [...new Set(items)];
const withFiles = (...groups) => unique(groups.flat());

const numberedItems = (prefix, steps) => steps.map((label, index) => ({
  id: `${prefix}-${String(index + 1).padStart(4, '0')}`,
  label,
  critical: index < 12,
}));

const flow = ({ category, name, slug, version = '2.0.0', relatedFiles, steps }) => ({
  id: slug,
  category,
  name,
  version,
  relatedFiles,
  items: numberedItems(slug, steps),
});

const openAppSteps = [
  'Open Yardit in the browser.',
  'Confirm the Yardit logo appears in the header.',
  'Confirm the Home map area appears on the screen.',
  'Confirm no full-page error message appears.',
  'Confirm the Post Sale button appears in the header.',
];

const authGateSteps = [
  'Click Post Sale.',
  'If logged out, confirm the login or sign-up modal appears.',
  'Click the modal close button.',
  'Confirm the modal closes and the Home page remains visible.',
  'Click Post Sale again.',
  'Click Log In or Sign Up in the modal.',
  'Complete login with the test seller account.',
  'Confirm Yardit returns to the Home page after login.',
  'Click Post Sale again.',
  'If the verified address modal appears, confirm the modal title is visible.',
  'Confirm the verified address modal explains that an address is required.',
  'Click the Add Address or Profile action in the modal.',
  'Confirm the Profile page opens.',
  'Click the primary address field or edit address button.',
  'Type the test street address.',
  'Confirm address suggestions appear when available.',
  'Select the correct address suggestion.',
  'Click Confirm Address or Save Address.',
  'Confirm address verification or confirmation success appears.',
  'Return to the Home page.',
  'Click Post Sale again.',
];

const createListingStartSteps = [
  'Click Post Sale.',
];

const chooseResidentialSteps = [
  'Confirm the listing type selection screen appears.',
  'Confirm the Yard Sale option appears.',
  'Confirm the Neighborhood Sale option appears.',
  'Confirm the Event option appears.',
  'Click the Yard Sale option.',
  'Confirm the Residential Create Listing page loads.',
  'Confirm the first residential step is visible.',
];

const residentialFieldSteps = [
  'Confirm the title field is visible.',
  'Click the title field.',
  'Leave the title field blank.',
  'Click Continue.',
  'Confirm the title required validation message appears.',
  'Click the title field again.',
  'Type Yardit QA Free Sale Test.',
  'Confirm the title text appears exactly as typed.',
  'Confirm the description field is visible.',
  'Click the description field.',
  'Type tables, tools, toys, clothes, books, and home goods.',
  'Confirm the description text appears exactly as typed.',
  'Confirm the live description counter appears beneath the field.',
  'Confirm the Yard Sale counter shows the current count out of 500 characters.',
  'Type until the counter reaches 450 / 500 and confirm the counter visually warns the user.',
  'Type or paste more than 500 characters and confirm typing is capped at 500 / 500.',
  'Confirm no minimum description is required by clearing the description field and continuing after required category/title fields are valid.',
  'Confirm category controls are visible.',
  'Click the Furniture category if visible.',
  'Confirm Furniture appears selected.',
  'Click the Tools category if visible.',
  'Confirm Tools appears selected.',
  'Click Continue.',
  'Confirm the app moves to the location step.',
  'Click Back.',
  'Confirm title, description, and categories remain saved.',
  'Click Continue again.',
];

const locationAtomicSteps = [
  'Confirm the address search field is visible.',
  'Click the address search field.',
  'Type 874 Asheville St.',
  'Confirm typed address appears in the address field.',
  'Pause until suggestions load.',
  'Confirm at least one address suggestion appears.',
  'Click the 874 Asheville St, Lindsay CA suggestion if visible.',
  'Confirm the selected address appears in the address summary.',
  'Confirm city displays Lindsay if the city field is visible.',
  'Confirm state displays CA if the state field is visible.',
  'Confirm ZIP displays the correct ZIP if the ZIP field is visible.',
  'Confirm the map preview is visible.',
  'Confirm a map pin appears on the preview map.',
  'Click the map preview once near the selected address if pin placement is allowed.',
  'Confirm the map pin moves or remains anchored according to app rules.',
  'Click Continue.',
  'Confirm the app moves to the schedule step.',
  'Click Back.',
  'Confirm the selected address remains saved.',
  'Click Continue again.',
];

const freeLocationSteps = [
  'Confirm the address search field is visible.',
  'Click the address search field.',
  'Type 874 Asheville St.',
  'Confirm typed address appears in the address field.',
  'Pause until suggestions load.',
  'Confirm at least one address suggestion appears.',
  'Click the 874 Asheville St, Lindsay CA suggestion if visible.',
  'Confirm the selected address appears in the address summary.',
  'Confirm city displays Lindsay if the city field is visible.',
  'Confirm state displays CA if the state field is visible.',
  'Confirm ZIP displays the correct ZIP if the ZIP field is visible.',
  'Confirm the map preview is visible.',
  'Confirm a map pin appears on the preview map.',
  'Click Continue.',
  'Confirm the app moves to the next free-listing step without asking for selected dates or future dates.',
  'Click Back.',
  'Confirm the selected address remains saved.',
  'Click Continue again.',
];

const scheduleAtomicSteps = [
  'Confirm the schedule step is visible.',
  'Confirm the start date control is visible.',
  'Click the start date control.',
  'Select a valid future date.',
  'Confirm the selected start date appears highlighted or displayed.',
  'Confirm the end date control is visible if a range is allowed.',
  'Click the end date control if visible.',
  'Select the same date or a later valid date.',
  'Confirm the selected end date appears highlighted or displayed.',
  'Confirm the open time field is visible.',
  'Click the open time field.',
  'Enter or select 08:00 AM.',
  'Confirm 08:00 AM appears in the open time field.',
  'Confirm the close time field is visible.',
  'Click the close time field.',
  'Enter or select 07:00 AM.',
  'Click Continue.',
  'Confirm a validation message appears because close time is before open time.',
  'Click the close time field again.',
  'Enter or select 02:00 PM.',
  'Confirm 02:00 PM appears in the close time field.',
  'Click Continue.',
  'Confirm the app moves to the next step.',
  'Click Back.',
  'Confirm start date, end date, open time, and close time remain saved.',
  'Click Continue again.',
];

const photoAtomicSteps = [
  'Confirm the photo upload step or photo area is visible if photos are part of this flow.',
  'Click the photo upload button or upload drop zone if visible.',
  'Select one valid image file.',
  'Confirm upload progress or loading feedback appears if available.',
  'Confirm the uploaded image thumbnail appears.',
  'Click the photo upload button again if multiple photos are allowed.',
  'Select a second valid image file.',
  'Confirm a second thumbnail appears.',
  'Click remove on the second thumbnail if remove is available.',
  'Confirm the second thumbnail disappears.',
  'Confirm the first thumbnail remains visible.',
  'Click Continue.',
  'Confirm the app moves to the tier or review step.',
];

const tierSteps = (tier) => [
  'Confirm the tier selection step is visible.',
  'Confirm the Free tier option is visible.',
  'Confirm the Featured tier option is visible.',
  'Confirm the Premium tier option is visible.',
  `Click the ${tier} tier option.`,
  `Confirm the ${tier} tier option shows selected styling.`,
  `Confirm the ${tier} tier price or free label is visible.`,
  `Confirm the ${tier} tier benefits or badge description is visible.`,
  'Click Continue or Review Listing.',
  'Confirm the listing preview step opens.',
];

const freeTierSteps = [
  'Confirm the tier selection step is visible.',
  'Confirm the Free tier option is visible.',
  'Confirm the Featured tier option is visible.',
  'Confirm the Premium tier option is visible.',
  'Click the Free tier option.',
  'Confirm the Free tier option shows selected styling.',
  'Confirm the Free tier price or free label is visible.',
  'Confirm no payment review step is required for the Free tier.',
  'Click Publish Free Listing or Submit Listing.',
  'Confirm the listing publishes directly after the Free tier action.',
];

const premiumComingSoonSetupSteps = [
  'Confirm Premium early visibility or Coming Soon options are visible.',
  'Click the early visibility day selector if visible.',
  'Select one early visibility day if available.',
  'Confirm the early visibility selection appears selected.',
  'Confirm the preview summary includes Coming Soon or early visibility information.',
];

const previewAtomicSteps = (tier) => [
  'Confirm the listing preview page is visible.',
  'Confirm the preview title matches the title entered earlier.',
  'Confirm the preview description matches the description entered earlier.',
  'Confirm the preview address matches the selected address.',
  'Confirm the preview date range matches the selected dates.',
  'Confirm the preview open time matches 08:00 AM.',
  'Confirm the preview close time matches 02:00 PM.',
  'Confirm the preview category badges match the selected categories.',
  `Confirm the preview shows the ${tier} tier badge.`,
  'Confirm uploaded photo thumbnail appears in preview if a photo was uploaded.',
  'Click Back or Edit from the preview if available.',
  'Confirm the previous step opens.',
  'Click Continue or Review Listing again.',
  'Confirm the preview opens again with the same saved information.',
];

const freeSubmitSteps = [
  'Confirm a saving or publishing state appears.',
  'Confirm a success message appears.',
  'Confirm the Free listing flow is complete after publishing, with no review or checkout step.',
  'Click View My Listings if a button appears.',
  'Confirm My Listings opens.',
  'Confirm the new listing card appears.',
  'Confirm the listing card shows a Free badge.',
  'Confirm the listing card does not require selected dates or future dates.',
];

const paymentAtomicSteps = (tier) => [
  `Click Continue to Payment for the ${tier} listing.`,
  'Confirm the payment review screen opens.',
  'Confirm the listing title appears on the payment review screen.',
  `Confirm the selected tier shows ${tier}.`,
  'Confirm the total amount due is visible.',
  'Confirm the non-refundable purchase notice appears if required.',
  'If an acknowledgement checkbox appears, click the checkbox.',
  'Confirm the acknowledgement checkbox becomes checked.',
  'Click Checkout or Pay Now.',
  'Confirm a checkout loading state appears.',
  'Confirm Stripe Checkout opens.',
  'Confirm the checkout amount matches the Yardit review amount.',
  'Confirm the checkout description refers to the selected listing or Yardit purchase.',
  'Confirm over-limit residential descriptions are blocked before checkout starts.',
  'Enter the payment card number.',
  'Enter the card expiration date.',
  'Enter the card CVC.',
  'Enter billing ZIP code if requested.',
  'Click Pay or Submit Payment.',
  'Confirm Stripe shows payment processing feedback.',
  'Confirm Yardit success return page opens.',
  'Confirm a success message appears in Yardit.',
  'Open My Listings.',
  'Confirm the paid listing card appears.',
  `Confirm the card shows the ${tier} badge.`,
  'Confirm payment status shows paid or active.',
];

const paymentCancelRetrySteps = [
  'Start a paid checkout again with a separate test listing or upgrade.',
  'Click Checkout or Pay Now.',
  'Confirm Stripe Checkout opens.',
  'Click browser back, cancel, or close checkout according to the available Stripe control.',
  'Confirm Yardit returns to a cancel or unpaid state.',
  'Confirm paid tier benefits are not granted after cancellation.',
  'Click Retry Payment or restart the checkout action.',
  'Confirm a new checkout attempt opens.',
  'Cancel the retry checkout.',
  'Confirm the listing remains unpaid or unchanged after the second cancellation.',
];

const receiptAtomicSteps = [
  'Open My Listings.',
  'Find the paid listing card.',
  'Click Receipt, Billing, or Payment History action if visible.',
  'Confirm the receipt or billing panel opens.',
  'Confirm the receipt shows listing title.',
  'Confirm the receipt shows amount paid.',
  'Confirm the receipt shows payment status.',
  'Confirm the receipt shows payment date.',
  'Confirm the receipt shows transaction ID or checkout reference if available.',
  'Click Close or Back from the receipt.',
  'Confirm My Listings is visible again.',
];

const publicVisibilityAtomicSteps = (statusLabel) => [
  'Open Home map as a public viewer or non-owner account.',
  'Click the map search field.',
  'Type Lindsay CA.',
  'Submit the search.',
  'Confirm the map moves to Lindsay CA.',
  'Confirm eligible listing pins appear after loading.',
  'Find the test listing pin if it is inside the current public visibility window.',
  `Confirm the test listing displays the expected ${statusLabel} status or badge.`,
  'Click the test listing pin.',
  'Confirm the popup opens.',
  'Confirm popup title matches the listing title.',
  'Confirm popup date matches the listing dates.',
  'Confirm popup time matches Open/Close hours.',
  'Confirm popup tier/status badge is correct.',
  'Click List View.',
  'Confirm list view opens.',
  'Confirm the same listing appears in list view when it is visible on the map.',
  'Open filters.',
  'Turn off the matching listing type filter.',
  'Confirm the listing disappears from list view.',
  'Confirm the listing disappears from map view.',
  'Turn the matching listing type filter back on.',
  'Confirm the listing appears again when visibility rules allow it.',
];

const freeVisibilitySteps = [
  'Open Home map as a public viewer or non-owner account.',
  'Click the map search field.',
  'Type Lindsay CA.',
  'Submit the search.',
  'Confirm the map moves to Lindsay CA.',
  'Confirm eligible listing pins appear after loading.',
  'Find the free test listing pin if it is publicly visible under current app rules.',
  'Click the free test listing pin.',
  'Confirm the popup opens.',
  'Confirm popup title matches the listing title.',
  'Confirm popup tier/status badge is correct for a Free listing.',
  'Confirm the popup does not require selected dates or future dates for the Free listing.',
  'Click List View.',
  'Confirm list view opens.',
  'Confirm the same Free listing appears in list view when visible on the map.',
  'Open filters.',
  'Turn off the matching listing type filter.',
  'Confirm the listing disappears from list view.',
  'Confirm the listing disappears from map view.',
  'Turn the matching listing type filter back on.',
  'Confirm the listing appears again when visibility rules allow it.',
];

const ownerPreviewSteps = [
  'Log in as the listing owner.',
  'Open Home map.',
  'Confirm the owner preview toggle appears if available.',
  'Turn owner preview on.',
  'Confirm owner-only scheduled or hidden preview listings appear if eligible.',
  'Confirm preview-only listings show clear preview or owner context.',
  'Turn owner preview off.',
  'Confirm preview-only listings disappear from the normal public map state.',
  'Open List View with owner preview on.',
  'Confirm preview listing appears in list view.',
  'Turn owner preview off.',
  'Confirm preview listing disappears from list view if not public.',
];

const editAtomicSteps = [
  'Log in as the owner of the test residential listing.',
  'Open My Listings.',
  'Click the Active tab.',
  'Find the target listing card.',
  'Confirm the Edit button is visible.',
  'Click Edit.',
  'Confirm the edit modal or edit page opens.',
  'Confirm the title field contains the current title.',
  'Click the title field.',
  'Select the existing title text.',
  'Type an updated listing title.',
  'Confirm the updated title appears in the title field.',
  'Click the description field.',
  'Add updated description text.',
  'Confirm the updated description appears.',
  'Confirm the edit description counter appears beneath the field with the correct limit for the listing type.',
  'If editing an older over-limit description, confirm the full old text loads normally.',
  'Try saving an over-limit description and confirm save is blocked until the text is reduced below the limit.',
  'Reduce the description to the allowed limit or below and confirm save succeeds.',
  'Click a category checkbox to add or remove it.',
  'Confirm the category selected state changes.',
  'Click the open time field.',
  'Change open time to 09:00 AM.',
  'Confirm 09:00 AM appears.',
  'Click the close time field.',
  'Change close time to 03:00 PM.',
  'Confirm 03:00 PM appears.',
  'Click Save.',
  'Confirm saving feedback appears.',
  'Confirm the edit modal closes or success message appears.',
  'Confirm the My Listings card shows the updated title.',
  'Open Listing Detail.',
  'Confirm the detail page shows updated title, description, categories, and hours.',
];

const upgradeAtomicSteps = [
  'Log in as owner of a Free residential listing.',
  'Open My Listings.',
  'Find the Free listing card.',
  'Confirm the Upgrade button is visible.',
  'Click Upgrade.',
  'Confirm the upgrade modal opens.',
  'Confirm Featured upgrade option is visible.',
  'Confirm Premium upgrade option is visible.',
  'Click Featured upgrade option.',
  'Confirm Featured option appears selected.',
  'Confirm Featured upgrade price appears.',
  'Click Continue to Checkout.',
  'Confirm checkout loading state appears.',
  'Confirm Stripe Checkout opens.',
  'Cancel checkout before paying.',
  'Confirm Yardit returns without upgrading the listing.',
  'Confirm the listing card still shows Free badge.',
  'Click Upgrade again.',
  'Click Premium upgrade option.',
  'Confirm Premium option appears selected.',
  'Click Continue to Checkout.',
  'Complete payment successfully.',
  'Confirm Yardit success screen appears.',
  'Open My Listings.',
  'Confirm the listing card shows Premium badge.',
  'Open Home map.',
  'Confirm the listing pin uses Premium styling when visible.',
];

const expirationRelistAtomicSteps = [
  'Log in as owner of an expired residential listing.',
  'Open My Listings.',
  'Click the Expired tab.',
  'Confirm the expired listing card appears.',
  'Confirm the card shows an Expired badge.',
  'Open Home map in a public viewer session.',
  'Confirm the expired listing does not appear on the public map.',
  'Open List View in the public viewer session.',
  'Confirm the expired listing does not appear in public list results.',
  'Return to the owner My Listings session.',
  'Click Relist on the expired listing card.',
  'Confirm the relist modal or relist page opens.',
  'Confirm previous listing title is visible if prefilled.',
  'Select a new future date.',
  'Confirm the new date appears selected.',
  'Enter a valid open time.',
  'Confirm the open time appears.',
  'Enter a valid close time.',
  'Confirm the close time appears.',
  'Click Save Relist or Publish.',
  'Confirm success message appears.',
  'Confirm listing moves out of the Expired tab.',
  'Click Active or Scheduled tab.',
  'Confirm the relisted listing appears in the correct tab.',
];

const neighborhoodStartSteps = [
  'Click Post Sale.',
  'Confirm the listing type screen opens.',
  'Confirm Neighborhood Sale option is visible.',
  'Click Neighborhood Sale.',
  'Confirm the Neighborhood Sale intro screen opens.',
  'Confirm organizer instructions are visible.',
  'Click Start or Continue.',
  'Confirm organizer setup screen opens.',
];

const neighborhoodOrganizerSteps = [
  'Confirm neighborhood sale title field is visible.',
  'Click the neighborhood sale title field.',
  'Leave the title field blank.',
  'Click Continue.',
  'Confirm title validation message appears.',
  'Type Lindsay Block Sale Test into the title field.',
  'Confirm the title appears in the field.',
  'Confirm description field is visible.',
  'Click description field.',
  'Type Saturday neighborhood sale with multiple homes participating.',
  'Confirm description appears in the field.',
  'Confirm the live counter appears under the Neighborhood Sale description field.',
  'Confirm the Neighborhood Sale counter shows the current count out of 1000 characters.',
  'Type until the counter reaches 900 / 1000 and confirm the counter visually warns the user.',
  'Type or paste more than 1000 characters and confirm typing is capped at 1000 / 1000.',
  'Clear the description and confirm there is no minimum description requirement.',
  'Confirm organizer participation options are visible.',
  'Click Participating Organizer.',
  'Confirm participating organizer option appears selected.',
  'Confirm organizer listing fields appear.',
  'Click Continue.',
  'Confirm app moves to host address or location step.',
];

const neighborhoodRadiusSteps = [
  'Confirm host address field is visible.',
  'Click host address field.',
  'Type 874 Asheville St, Lindsay CA.',
  'Confirm address suggestions appear.',
  'Select the correct host address suggestion.',
  'Confirm host address summary appears.',
  'Confirm host map preview appears.',
  'Confirm radius preview or validation context appears if available.',
  'Click Continue.',
  'Confirm app moves to participant/radius or schedule step.',
  'Open join flow as a second user.',
  'Click Ask To Join on the public neighborhood sale page.',
  'Confirm join modal opens.',
  'Click participant address field.',
  'Type an address outside the allowed radius.',
  'Click Validate or Continue.',
  'Confirm out-of-radius validation message appears.',
  'Confirm the submit button remains blocked or the user cannot continue.',
  'Replace address with an address inside the allowed radius.',
  'Click Validate or Continue.',
  'Confirm radius validation success appears.',
];

const neighborhoodParticipantSteps = [
  'Confirm participant sale title field is visible.',
  'Click participant sale title field.',
  'Type Participant Yard Sale Test.',
  'Confirm participant title appears.',
  'Click participant description field.',
  'Type clothes, tools, books, and kids items.',
  'Confirm participant description appears.',
  'Select one participant sale category.',
  'Confirm selected category shows selected state.',
  'Confirm participant date matches the neighborhood sale date if locked by organizer.',
  'Confirm participant open time matches organizer time if locked by organizer.',
  'Click Submit Join Request.',
  'Confirm pending request success message appears.',
  'Open My Listings as participant.',
  'Confirm participant listing appears with Pending status.',
];

const neighborhoodApprovalSteps = [
  'Log in as the neighborhood sale organizer.',
  'Open My Listings.',
  'Find the neighborhood sale organizer card.',
  'Confirm HOST badge appears on the organizer card.',
  'Confirm Upgrade button is not visible on the neighborhood sale card.',
  'Click View Listing or Manage.',
  'Confirm organizer view opens.',
  'Confirm pending participant request appears.',
  'Click Approve on the pending participant.',
  'Confirm approval confirmation appears if the app uses one.',
  'Confirm participant status changes to Approved.',
  'Confirm approved participant appears in approved homes list.',
  'Confirm home count increases by one.',
  'Confirm billing total updates if pricing changes.',
  'Open Home map as public viewer during active visibility.',
  'Confirm approved participant pin appears on the map.',
  'Create or locate another pending participant request.',
  'Click Deny on that pending request.',
  'Confirm denial modal or prompt appears if used.',
  'Enter denial reason if field appears.',
  'Click Confirm Deny.',
  'Confirm participant status changes to Denied.',
  'Confirm denied participant does not appear on public map.',
  'Select an approved participant.',
  'Click Remove Participant.',
  'Confirm removal confirmation appears.',
  'Enter removal reason if required.',
  'Click Confirm Remove.',
  'Confirm participant leaves approved list.',
  'Confirm home count decreases by one.',
  'Confirm removed participant pin no longer appears publicly.',
];

const neighborhoodBillingSteps = [
  'Open organizer neighborhood sale detail page.',
  'Confirm Billing section is visible.',
  'Confirm billing total is visible without expanding transaction history.',
  'Click or expand Billing details.',
  'Confirm transaction history area appears.',
  'Confirm flat $49.99 price line appears.',
  'Confirm no variable home-count price line appears.',
  'Confirm charged amount line appears.',
  'Confirm payment status line appears.',
  'Approve a participant or use a sale with adjusted home count.',
  'Refresh or reopen Billing section.',
  'Confirm the Neighborhood Sale price remains $49.99.',
  'Confirm checkout or saved-card charge amount is $49.99 when the sale activates.',
  'Confirm successful payment updates billing status.',
  'Return to organizer view.',
  'Confirm payment transaction appears in Billing history.',
];

const neighborhoodVisibilitySteps = [
  'Open Home map before neighborhood active date if Coming Soon should apply.',
  'Confirm neighborhood sale pin appears with Coming Soon badge when eligible.',
  'Click neighborhood sale pin.',
  'Confirm popup shows neighborhood sale title.',
  'Confirm popup shows participant count.',
  'Confirm popup shows sale dates and hours.',
  'Open public detail view.',
  'Confirm public view hides organizer-only approval controls.',
  'Confirm public view shows join/share actions when eligible.',
  'Open Home map during active neighborhood sale hours.',
  'Confirm neighborhood sale pin appears active.',
  'Confirm approved participant pins appear active.',
  'Log in as organizer.',
  'Open organizer detail view.',
  'Confirm organizer view shows participant controls.',
  'Confirm organizer view shows billing controls.',
  'Confirm organizer view shows activation state.',
];

const mapInitialSteps = [
  'Open Yardit Home page.',
  'Confirm map area appears.',
  'Confirm map tiles render.',
  'Confirm current location button appears.',
  'Confirm search field appears.',
  'Confirm filters button appears.',
  'Confirm list view control appears if available.',
  'Click search field.',
  'Type Lindsay CA.',
  'Confirm typed text appears.',
  'Press Enter or click search submit.',
  'Confirm map pans or zooms to Lindsay CA.',
  'Confirm result pins refresh after search.',
  'Click current location button.',
  'Confirm browser permission prompt appears if permission has not been decided.',
  'Click Allow in the browser permission prompt.',
  'Confirm map centers near current location.',
  'Reload in a browser profile with location blocked.',
  'Click current location button.',
  'Click Block or Deny in browser prompt.',
  'Confirm Yardit shows a location permission message.',
  'Confirm app remains usable after permission denial.',
];

const mapFilterSteps = [
  'Click the Filters button.',
  'Confirm filter modal or filter panel opens.',
  'Confirm Residential filter option appears.',
  'Confirm Neighborhood Sale filter option appears.',
  'Confirm Event filter option appears if event discovery is enabled.',
  'Click Residential filter off.',
  'Confirm residential pins disappear from the map.',
  'Confirm residential rows disappear from list view.',
  'Click Residential filter on.',
  'Confirm residential pins return when eligible.',
  'Click Neighborhood Sale filter off.',
  'Confirm neighborhood pins disappear.',
  'Click Neighborhood Sale filter on.',
  'Confirm neighborhood pins return when eligible.',
  'Click any date filter if available.',
  'Select a future date.',
  'Confirm map results update for that date.',
  'Click Reset Filters.',
  'Confirm all default filters return.',
  'Confirm map and list results refresh.',
  'Close the filter panel.',
  'Confirm the Home map is visible again.',
];

const mapClusterPinSteps = [
  'Search or pan to an area with multiple nearby listings.',
  'Click the zoom out control.',
  'Confirm nearby pins group into a cluster.',
  'Confirm the cluster displays a count.',
  'Click the cluster marker.',
  'Confirm the map zooms in or expands the cluster.',
  'Click the zoom in control until individual pins show.',
  'Confirm residential pins use residential styling.',
  'Confirm neighborhood pins use neighborhood styling if present.',
  'Click one individual pin.',
  'Confirm popup opens.',
  'Confirm popup title appears.',
  'Confirm popup date appears.',
  'Confirm popup time appears.',
  'Confirm popup address or location label appears.',
  'Confirm popup badge appears.',
  'Click the popup close button.',
  'Confirm popup closes.',
  'Click the pin again.',
  'Click View Details in the popup.',
  'Confirm detail page or detail panel opens.',
  'Click browser back or close detail.',
  'Confirm Home map returns to the previous area.',
];

const mapActionSteps = [
  'Click a visible listing pin.',
  'Confirm popup opens.',
  'Click Add Stop or Join the Hunt if visible.',
  'Confirm the route builder or hunt panel updates with one stop.',
  'Click a second listing pin.',
  'Click Add Stop.',
  'Confirm route builder shows two stops.',
  'Click remove on the first stop.',
  'Confirm the route builder shows one stop.',
  'Click Bookmark or Save on a listing popup or detail card.',
  'If login is required, confirm login modal opens.',
  'Log in if needed.',
  'Click Bookmark or Save again.',
  'Confirm saved icon changes state.',
  'Click Bookmark or Save again.',
  'Confirm saved icon returns to unsaved state.',
  'Click Report.',
  'Confirm report modal opens.',
  'Click Cancel or close on the report modal.',
  'Confirm report modal closes.',
];

const myListingsTabsSteps = [
  'Log in as a user with multiple listing statuses.',
  'Open the account menu.',
  'Click My Listings.',
  'Confirm My Listings page loads.',
  'Confirm Active tab appears.',
  'Click Active tab.',
  'Confirm active cards appear.',
  'Confirm active card badges appear at the top on mobile width.',
  'Confirm active card action buttons appear at the bottom on mobile width.',
  'Confirm Scheduled tab appears.',
  'Click Scheduled tab.',
  'Confirm scheduled cards appear.',
  'Confirm Scheduled badge appears on scheduled cards.',
  'Confirm Expired tab appears.',
  'Click Expired tab.',
  'Confirm expired cards appear.',
  'Confirm Expired badge appears on expired cards.',
  'Click Hidden tab if visible.',
  'Confirm hidden cards appear with Hidden badge.',
  'Click Canceled tab if visible.',
  'Confirm canceled cards appear with Canceled badge.',
];

const myListingsSearchActionSteps = [
  'Click the My Listings search field.',
  'Type part of a listing title.',
  'Confirm matching cards remain visible.',
  'Confirm non-matching cards are hidden.',
  'Clear the search field.',
  'Confirm all cards in the selected tab return.',
  'Open filters if filter controls are visible.',
  'Select a listing type filter.',
  'Confirm only matching listing type cards remain.',
  'Select a tier filter if available.',
  'Confirm only matching tier cards remain.',
  'Click Reset or clear filters.',
  'Confirm cards return to the default tab results.',
  'Click View Listing on a card.',
  'Confirm Listing Detail opens for that exact listing.',
  'Return to My Listings.',
  'Click Edit on an editable card.',
  'Confirm edit modal opens.',
  'Close edit modal.',
  'Click Upgrade on an eligible residential card.',
  'Confirm upgrade modal opens.',
  'Close upgrade modal.',
  'Find a neighborhood sale card.',
  'Confirm the neighborhood sale card shows HOST badge when organizer owns it.',
  'Confirm the neighborhood sale card does not show Upgrade button.',
  'Click Receipt or Billing on a paid card.',
  'Confirm receipt or billing view opens.',
  'Close receipt or billing view.',
];

const detailAllSteps = [
  'Open a listing detail page from a map popup or list row.',
  'Confirm listing title appears.',
  'Confirm photo section appears.',
  'Click first photo if clickable.',
  'Confirm photo viewer opens or photo enlarges.',
  'Click next photo if multiple photos exist.',
  'Confirm next photo displays.',
  'Click close on photo viewer if opened.',
  'Confirm detail page is visible again.',
  'Confirm description section appears.',
  'Confirm category badges appear.',
  'Confirm tier badge appears.',
  'Confirm status badge appears.',
  'Confirm date range appears.',
  'Confirm Open/Close hours appear.',
  'Confirm address or location label appears.',
  'Click Share.',
  'Confirm native share, copy link, or share feedback appears.',
  'Complete copy/share action if prompted.',
  'Confirm share success feedback appears if provided.',
  'Click Bookmark or Save.',
  'Confirm saved state appears.',
  'Click Bookmark or Save again.',
  'Confirm unsaved state appears.',
  'Click Add Stop or route action if visible.',
  'Confirm route builder updates.',
  'Click Report.',
  'Confirm report modal opens.',
  'Click close on report modal.',
  'Confirm report modal closes.',
];

const profileAuthSteps = [
  'Open Yardit while logged out.',
  'Click Log In / Sign Up.',
  'Confirm authentication screen opens.',
  'Click Sign Up if a sign-up option is shown.',
  'Click email field.',
  'Enter a new test email address.',
  'Click password field if visible.',
  'Enter a valid password if visible.',
  'Click submit or continue.',
  'Confirm registration continues or verification prompt appears.',
  'Complete available verification steps for the test account.',
  'Confirm Yardit opens after authentication.',
  'Confirm name collection modal appears if the new account has no name.',
  'Click name field.',
  'Leave name blank.',
  'Click Save or Continue.',
  'Confirm name validation message appears.',
  'Type the tester name.',
  'Confirm name appears in the field.',
  'If terms checkbox appears, click Continue without checking it.',
  'Confirm terms validation or blocker appears.',
  'Click the terms checkbox.',
  'Confirm checkbox becomes checked.',
  'Click Save or Continue.',
  'Confirm modal closes.',
  'Open account menu.',
  'Click Logout.',
  'Confirm logged-out state appears.',
  'Click Log In / Sign Up again.',
  'Click Forgot Password if visible.',
  'Confirm forgot password screen opens.',
  'Enter email address.',
  'Click Submit reset request.',
  'Confirm reset confirmation appears.',
];

const profileAddressSettingsSteps = [
  'Log in as a test user.',
  'Open account menu.',
  'Click My Profile.',
  'Confirm Profile page loads.',
  'Confirm name appears.',
  'Confirm email appears.',
  'Confirm primary address section appears.',
  'Click Add Address or Edit Address.',
  'Confirm address entry fields appear.',
  'Click Save with address blank.',
  'Confirm address validation message appears.',
  'Click street address field.',
  'Type 874 Asheville St.',
  'Confirm typed street appears.',
  'Click city field if manual city field appears.',
  'Type Lindsay if needed.',
  'Click state field if manual state field appears.',
  'Type CA if needed.',
  'Click ZIP field if manual ZIP field appears.',
  'Type the test ZIP if needed.',
  'Click Confirm Address or Save.',
  'Confirm address review or map confirmation appears.',
  'Click Confirm.',
  'Confirm address verification status becomes confirmed or verified.',
  'Click Edit Address again.',
  'Change one address value.',
  'Confirm reverification is required after changing address.',
  'Confirm phone number is not required for residential listing creation.',
  'Leave optional phone field blank if present.',
  'Click Save Profile if visible.',
  'Confirm Profile saves without requiring phone number.',
  'Open Settings.',
  'Confirm Settings page loads.',
  'Change a visible setting.',
  'Click Save.',
  'Confirm setting save feedback appears.',
  'Refresh the page.',
  'Confirm the setting remains saved.',
];

const notificationSteps = [
  'Log in as a user with at least one notification.',
  'Confirm notification bell icon appears in the header.',
  'Confirm unread badge appears if unread notifications exist.',
  'Click the notification bell.',
  'Confirm notification popup opens.',
  'Confirm notification title appears in the popup.',
  'Confirm notification message appears in the popup.',
  'Confirm unread notification styling is visible if unread exists.',
  'Click the first unread notification.',
  'Confirm notification marks read or navigates to related page.',
  'Return to the previous page if navigation occurred.',
  'Click notification bell again.',
  'Confirm the unread count changed or unread styling cleared.',
  'Click View All.',
  'Confirm Notifications page opens.',
  'Confirm read notifications are visible.',
  'Confirm unread notifications are visible if any remain.',
  'Click a notification with a listing link if available.',
  'Confirm related listing or page opens.',
  'Return to Home.',
  'Click notification bell.',
  'Click outside the popup.',
  'Confirm popup closes automatically.',
];

const supportSteps = [
  'Open Contact Support page.',
  'Confirm support form loads.',
  'Confirm support category controls appear.',
  'Click Residential category.',
  'Confirm Residential category appears selected.',
  'Click Submit with required fields blank.',
  'Confirm required field validation appears.',
  'Click name field if visible.',
  'Type Test User.',
  'Click email field.',
  'Type test email address.',
  'Confirm phone number is not required for support submission unless explicitly optional.',
  'Click description field.',
  'Type support issue details.',
  'Click photo upload if available.',
  'Select a valid image file if upload is available.',
  'Confirm uploaded image preview appears if upload is available.',
  'Click Submit.',
  'Confirm submitting state appears.',
  'Confirm success message appears.',
  'Confirm ticket number appears if provided.',
  'Open My Support Tickets.',
  'Confirm the submitted ticket appears.',
  'Confirm ticket status appears.',
  'Click the ticket row.',
  'Confirm ticket history or detail opens.',
  'Confirm submitted description appears.',
  'Confirm submitted photo appears if one was uploaded.',
  'Log in as admin.',
  'Open Support Queue.',
  'Confirm the submitted ticket appears in the correct queue.',
  'Click the ticket in admin queue.',
  'Change ticket status to In Review.',
  'Click Save status.',
  'Confirm status saves.',
];

const reportSteps = [
  'Open a public listing detail page as a logged-in non-owner.',
  'Click Report.',
  'Confirm report modal opens.',
  'Confirm report reason choices appear.',
  'Click Submit Report without selecting a reason.',
  'Confirm reason validation message appears.',
  'Click a report reason.',
  'Confirm selected reason appears selected.',
  'Confirm details field appears if required.',
  'Click details field.',
  'Type report details.',
  'Confirm typed details appear.',
  'Click upload screenshot if available.',
  'Select a valid image if upload is available.',
  'Confirm image preview appears if upload is available.',
  'Click Submit Report.',
  'Confirm submitting state appears.',
  'Confirm report success message appears.',
  'Confirm report modal closes or shows completed state.',
  'Log in as admin.',
  'Open Reports, Cases, or Support Queue.',
  'Confirm the new report appears.',
  'Click the report record.',
  'Confirm listing reference appears.',
  'Confirm reporter context appears for admin.',
  'Confirm reason and details appear.',
  'Change report review status.',
  'Click Save or Apply.',
  'Confirm review status saves.',
];

const earlyVisibilityPromoSteps = [
  'Log in as an admin who can manage residential promo codes.',
  'Open Admin Lite.',
  'Open Residential Promo Codes.',
  'Click Create Promo Code.',
  'Enter a unique test promo code.',
  'Enter a title for the promo code.',
  'Set status to Active.',
  'Confirm the regular discount settings are visible.',
  'Enable Early Visibility.',
  'Enter a valid number of days before the sale date.',
  'Save the promo code.',
  'Confirm the promo code appears in the promo list.',
  'Start creating a paid Yard Sale listing as a seller.',
  'Select a future start date that allows an early visibility window.',
  'Select a Featured or Premium paid tier.',
  'Continue to the payment step.',
  'Enter the early visibility promo code.',
  'Click Apply.',
  'Confirm the promo applies successfully.',
  'Confirm the payment total reflects the promo discount.',
  'Complete checkout or complete the free promo path if the discount is 100%.',
  'Open My Listings.',
  'Confirm the listing exists with the paid tier selected.',
  'Confirm listing billing or receipt information shows the promo/payment result.',
  'Open the listing record as admin if available.',
  'Confirm Early Visibility Enabled is stored on the listing.',
  'Confirm Early Visibility Days is stored on the listing.',
  'Confirm Visibility Start Date is not later than the sale start date.',
  'Confirm Early Visibility Promo Code matches the code used.',
  'Open Home map during the early visibility window.',
  'Confirm the listing appears as Coming Soon before its start date.',
  'Open List View during the early visibility window.',
  'Confirm the same listing appears as Coming Soon in list results.',
  'Open Home map during the actual open hours.',
  'Confirm the listing appears active instead of Coming Soon.',
  'Confirm the promo does not grant early visibility to unrelated listings.',
];

const residentialEventSteps = [
  'Start creating a new listing.',
  'Select Event as the listing type.',
  'Enter an event name.',
  'Enter an event description.',
  'Confirm the live counter appears under the Residential Event description field.',
  'Confirm the Residential Event counter shows the current count out of 1000 characters.',
  'Type until the counter reaches 900 / 1000 and confirm the counter visually warns the user.',
  'Type or paste more than 1000 characters and confirm typing is capped at 1000 / 1000.',
  'Clear the event description and confirm there is no minimum description requirement.',
  'Open the event category dropdown.',
  'Confirm event category icons appear in the dropdown.',
  'Select a specific event category.',
  'Continue to the event location step.',
  'Choose a valid event location.',
  'Continue to the date and time step.',
  'Select a single valid event date.',
  'Enter a valid start time.',
  'Enter a valid end time.',
  'Try selecting a multi-day event date range if the controls allow it.',
  'Confirm multi-day residential events are blocked or warned correctly.',
  'Continue to the add-ons step.',
  'Confirm the Base Event package summary is visible.',
  'Confirm the "STAND OUT WITH THESE AD ONS" section is visible.',
  'Expand Be Seen By More People.',
  'Select the Be Seen By More People add-on.',
  'Expand Animation and select an animation if available.',
  'Expand Flyer and upload or select a flyer if available.',
  'Expand Gallery and confirm gallery options are visible.',
  'Expand Custom Icon and choose or upload an icon if available.',
  'Expand Marquee and select the marquee add-on if available.',
  'Confirm the price summary updates as add-ons are selected.',
  'Continue to payment.',
  'Confirm Base Event plus selected add-ons are included in the payment total.',
  'Complete checkout using a test payment.',
  'Open My Listings.',
  'Confirm the event listing appears.',
  'Open Home map during the event visibility window.',
  'Confirm the event marker appears.',
  'Confirm the custom icon is used when the Custom Icon add-on was selected.',
  'Open the event detail page.',
  'Confirm event title, date, time, category, and location display correctly.',
  'Confirm flyer displays separately from the image gallery when selected.',
  'Confirm selected add-ons are reflected in the public experience.',
];

const paymentAuditSteps = [
  'Log in as an authorized admin.',
  'Open Payment Audit.',
  'Confirm the payment audit dashboard loads.',
  'Confirm summary cards appear.',
  'Run or refresh the audit scan if a scan action is available.',
  'Confirm scan loading feedback appears.',
  'Confirm audit findings or empty state appears after scanning.',
  'Open the status filter.',
  'Filter to open issues.',
  'Confirm only open findings appear.',
  'Search by listing ID, transaction ID, or user email if search is available.',
  'Confirm matching audit rows remain visible.',
  'Open an audit issue row.',
  'Confirm issue type, linked record, and transaction context are visible.',
  'Add a review note if the UI allows notes.',
  'Mark the issue reviewed, ignored, or resolved according to the test case.',
  'Confirm the review status saves.',
  'Refresh Payment Audit.',
  'Confirm the saved review status remains visible.',
  'Open the related listing or payment record if a link is provided.',
  'Confirm the related record matches the audit issue.',
];

const adminSteps = [
  'Log in as an authorized admin user.',
  'Open Admin Login or Admin Lite.',
  'Confirm Employee ID field appears.',
  'Click Employee ID field.',
  'Enter Employee ID.',
  'Confirm PIN field appears.',
  'Click PIN field.',
  'Enter PIN.',
  'Click Login.',
  'Confirm admin dashboard opens.',
  'Confirm dashboard summary cards appear.',
  'Click Residential Listings section.',
  'Confirm residential listing management opens.',
  'Click listing search field.',
  'Type a listing title or listing number.',
  'Confirm matching listings appear.',
  'Open status filter.',
  'Select Active status.',
  'Confirm active listings appear.',
  'Click a listing row.',
  'Confirm listing detail opens.',
  'Confirm title, owner, status, dates, hours, and payment state appear.',
  'Change status on a safe test listing.',
  'Click Save status.',
  'Confirm status save feedback appears.',
  'Open Neighborhood Sales section if available.',
  'Confirm neighborhood sales list appears.',
  'Open Users section.',
  'Click user search field.',
  'Type user email.',
  'Confirm matching user appears.',
  'Click user row.',
  'Confirm user detail opens.',
  'Open Support Queue.',
  'Confirm support tickets appear.',
  'Open Billing or Transactions section.',
  'Confirm payment transactions appear.',
  'Search transactions by user email or listing ID.',
  'Confirm matching transaction appears.',
  'Open the transaction detail if available.',
  'Confirm amount, status, Stripe IDs, user, and listing reference appear.',
];

const assistedReviewOnlySteps = [
  'Open Admin as an authorized admin user.',
  'Open Assisted Listings section.',
  'Confirm assisted listing records load.',
  'Confirm seller approval status appears on each record if available.',
  'Confirm listing number appears on each record if available.',
  'Click an assisted listing record to view details.',
  'Confirm detail view opens.',
  'Confirm QR code area appears only as allowed by the existing locked workflow.',
  'Confirm QR code image or QR status appears if already generated.',
  'Confirm approval URL or QR label appears if already present.',
  'Do not click regenerate QR.',
  'Do not edit QR token.',
  'Do not change QR expiration.',
  'Do not change seller approval state from this QA check unless a separate approved test requires it.',
  'Close the QR view or detail modal.',
  'Confirm no success message about QR regeneration appeared.',
  'Confirm assisted listing record remains unchanged after view-only check.',
];

const qaApprovalSteps = [
  'Open the Yardit QA Checklist System.',
  'Click a QA area in the left panel.',
  'Confirm the flow list updates for that QA area.',
  'Click a flow name.',
  'Confirm the selected flow opens.',
  'Confirm flow name appears at the top.',
  'Confirm flow version appears at the top.',
  'Confirm related files disclosure appears.',
  'Open related files disclosure.',
  'Confirm related files are listed.',
  'Mark the first checklist item Pass.',
  'Confirm the item checkbox fills or selected state changes.',
  'Enter Tested By for the item.',
  'Confirm Tested By text remains visible.',
  'Enter Tested Date for the item.',
  'Confirm Tested Date remains visible.',
  'Enter notes for the item.',
  'Confirm notes remain visible.',
  'Enter screenshot filename or note if needed.',
  'Confirm screenshot note remains visible.',
  'Continue marking every item in the flow Pass or Fail.',
  'Confirm failed items include notes.',
  'Enter approver name in Approved By field.',
  'Click Approve Flow.',
  'Confirm approval success message appears.',
  'Confirm approved flow name is saved.',
  'Confirm version is saved.',
  'Confirm Approved By is saved.',
  'Confirm Approved Date is saved.',
  'Confirm Related Files are saved.',
  'Refresh the page.',
  'Confirm approval details still appear.',
];

const qaFreezeSteps = [
  'Open the Yardit QA Checklist System.',
  'Select an approved flow.',
  'Confirm Approved badge appears.',
  'Confirm no Needs Retest warning appears.',
  'Click Freeze Flow.',
  'Confirm freeze success message appears.',
  'Confirm Frozen badge appears.',
  'Open related files disclosure.',
  'Confirm frozen related files are still visible.',
  'Change a flow version or related file list in a future controlled QA update.',
  'Reopen the QA Checklist System.',
  'Select the previously approved flow.',
  'Confirm Needs Retest badge appears when version or related files changed.',
  'Confirm Changed File or changed version text appears.',
  'Confirm Potentially Affected Flow displays the selected flow name.',
  'Retest the changed checklist items.',
  'Mark all retested items Pass.',
  'Enter approver name.',
  'Click Approve Flow again.',
  'Confirm Needs Retest warning clears after reapproval.',
];

export const QA_FLOWS = [
  flow({ category: 'Pre-Listing Setup', name: 'Open Yardit, Login, Verify Address', slug: 'pre-listing-open-login-verify-address', relatedFiles: withFiles(files.profile, files.residential), steps: [...openAppSteps, ...authGateSteps] }),

  flow({ category: 'Residential Listings', name: 'Free Listing', slug: 'residential-free-listing', relatedFiles: files.residential, steps: [...createListingStartSteps, ...chooseResidentialSteps, ...residentialFieldSteps, ...freeLocationSteps, ...photoAtomicSteps, ...freeTierSteps, ...freeSubmitSteps, ...freeVisibilitySteps, ...ownerPreviewSteps] }),
  flow({ category: 'Residential Listings', name: 'Featured Listing', slug: 'residential-featured-listing', relatedFiles: withFiles(files.residential, files.payments), steps: [...createListingStartSteps, ...chooseResidentialSteps, ...residentialFieldSteps, ...locationAtomicSteps, ...scheduleAtomicSteps, ...photoAtomicSteps, ...tierSteps('Featured'), ...previewAtomicSteps('Featured'), ...paymentAtomicSteps('Featured'), ...paymentCancelRetrySteps, ...receiptAtomicSteps, ...publicVisibilityAtomicSteps('Featured')] }),
  flow({ category: 'Residential Listings', name: 'Premium Listing', slug: 'residential-premium-listing', relatedFiles: withFiles(files.residential, files.payments), steps: [...createListingStartSteps, ...chooseResidentialSteps, ...residentialFieldSteps, ...locationAtomicSteps, ...scheduleAtomicSteps, ...photoAtomicSteps, ...tierSteps('Premium'), ...premiumComingSoonSetupSteps, ...previewAtomicSteps('Premium'), ...paymentAtomicSteps('Premium'), ...receiptAtomicSteps, ...publicVisibilityAtomicSteps('Premium')] }),
  flow({ category: 'Residential Listings', name: 'Premium Coming Soon', slug: 'residential-premium-coming-soon', relatedFiles: files.residential, steps: [...premiumComingSoonSetupSteps, ...publicVisibilityAtomicSteps('Coming Soon'), ...ownerPreviewSteps] }),
  flow({ category: 'Residential Listings', name: 'Open/Close Hours', slug: 'residential-open-close-hours', relatedFiles: files.residential, steps: [...scheduleAtomicSteps, ...publicVisibilityAtomicSteps('Open or Closed according to hours'), ...ownerPreviewSteps] }),
  flow({ category: 'Residential Listings', name: 'Listing Edit', slug: 'residential-listing-edit', relatedFiles: files.residential, steps: editAtomicSteps }),
  flow({ category: 'Residential Listings', name: 'Listing Upgrade', slug: 'residential-listing-upgrade', relatedFiles: withFiles(files.residential, files.payments), steps: [...upgradeAtomicSteps, ...receiptAtomicSteps] }),
  flow({ category: 'Residential Listings', name: 'Listing Expiration and Relist', slug: 'residential-expiration-relist', relatedFiles: files.residential, steps: expirationRelistAtomicSteps }),
  flow({ category: 'Residential Listings', name: 'Listing Preview, Payment, Receipt, Visibility', slug: 'residential-preview-payment-receipt-visibility', relatedFiles: withFiles(files.residential, files.payments), steps: [...previewAtomicSteps('selected'), ...paymentAtomicSteps('paid'), ...receiptAtomicSteps, ...publicVisibilityAtomicSteps('selected'), ...ownerPreviewSteps] }),

  flow({ category: 'Neighborhood Sales', name: 'Create Neighborhood Sale and Organizer Setup', slug: 'neighborhood-create-organizer', relatedFiles: files.neighborhood, steps: [...neighborhoodStartSteps, ...neighborhoodOrganizerSteps, ...neighborhoodRadiusSteps, ...scheduleAtomicSteps, ...neighborhoodBillingSteps, ...neighborhoodVisibilitySteps] }),
  flow({ category: 'Neighborhood Sales', name: 'Radius Validation and Ask To Join', slug: 'neighborhood-radius-ask-join', relatedFiles: files.neighborhood, steps: [...neighborhoodRadiusSteps, ...neighborhoodParticipantSteps] }),
  flow({ category: 'Neighborhood Sales', name: 'Home Approval, Approve, Deny, Remove Participant', slug: 'neighborhood-approval-deny-remove', relatedFiles: withFiles(files.neighborhood, files.notifications), steps: neighborhoodApprovalSteps }),
  flow({ category: 'Neighborhood Sales', name: 'Organizer Listing, Billing, Activation, Coming Soon, Public View, Organizer View', slug: 'neighborhood-billing-activation-views', relatedFiles: withFiles(files.neighborhood, files.payments), steps: [...neighborhoodBillingSteps, ...neighborhoodVisibilitySteps] }),

  flow({ category: 'Map / Home', name: 'Initial Load, Search, Filters, Location Permission', slug: 'map-initial-search-filters-location', relatedFiles: files.map, steps: [...mapInitialSteps, ...mapFilterSteps] }),
  flow({ category: 'Map / Home', name: 'Zoom Levels, Clustering, Pin Selection, Popup Actions', slug: 'map-zoom-cluster-pin-popup', relatedFiles: withFiles(files.map, files.detail), steps: mapClusterPinSteps }),
  flow({ category: 'Map / Home', name: 'Add Stop, Bookmark, Report, Route Builder, Coming Soon, Owner Preview Toggle', slug: 'map-actions-route-owner-preview', relatedFiles: withFiles(files.map, files.detail), steps: [...mapActionSteps, ...publicVisibilityAtomicSteps('Coming Soon'), ...ownerPreviewSteps] }),

  flow({ category: 'My Listings', name: 'Tabs, Active, Scheduled, Expired, Hidden, Canceled', slug: 'my-listings-tabs-statuses', relatedFiles: files.myListings, steps: myListingsTabsSteps }),
  flow({ category: 'My Listings', name: 'Search, Filters, Card Actions, View, Edit, Relist, Upgrade, Receipt, Billing', slug: 'my-listings-search-actions-billing', relatedFiles: withFiles(files.myListings, files.payments), steps: [...myListingsSearchActionSteps, ...editAtomicSteps, ...upgradeAtomicSteps, ...expirationRelistAtomicSteps, ...receiptAtomicSteps] }),

  flow({ category: 'Listing Detail', name: 'All Sections, Photos, Times, Dates, Badges, Report, Share, Bookmark, Route Actions', slug: 'listing-detail-all-actions', relatedFiles: files.detail, steps: detailAllSteps }),

  flow({ category: 'Profile', name: 'Registration, Login, Logout, Forgot Password, Name Collection, Terms Acceptance', slug: 'profile-auth-name-terms', relatedFiles: files.profile, steps: profileAuthSteps }),
  flow({ category: 'Profile', name: 'Profile Completion, Address Entry, Confirmation, Reverification, Phone, Email, Settings', slug: 'profile-address-settings', relatedFiles: files.profile, steps: profileAddressSettingsSteps }),

  flow({ category: 'Notifications', name: 'Bell Icon, Popup, View All, Read, Unread, Navigation, Auto Close', slug: 'notifications-complete', relatedFiles: files.notifications, steps: notificationSteps }),
  flow({ category: 'Support', name: 'Contact Support, Categories, Routing, Ticket Creation, Ticket Status, Ticket History', slug: 'support-complete', relatedFiles: files.support, steps: supportSteps }),
  flow({ category: 'Report Flow', name: 'Report Listing, Report User, Validation, Submission, Admin Review', slug: 'report-complete', relatedFiles: withFiles(files.detail, files.support), steps: reportSteps }),
  flow({ category: 'Payments', name: 'Checkout, Promo Codes, Success, Cancel, Retry, Receipts, Transactions, Billing Views', slug: 'payments-complete', relatedFiles: files.payments, steps: [...paymentAtomicSteps('selected paid tier'), ...paymentCancelRetrySteps, ...receiptAtomicSteps] }),
  flow({ category: 'Payments', name: 'Payment Audit Review', slug: 'payment-audit-review', relatedFiles: files.paymentAudit, steps: paymentAuditSteps }),

  flow({ category: 'Residential Promos', name: 'Early Visibility Promo Code', slug: 'residential-early-visibility-promo-code', relatedFiles: withFiles(files.residentialPromos, files.payments, files.map), steps: earlyVisibilityPromoSteps }),
  flow({ category: 'Residential Events', name: 'Base Event and Add-Ons', slug: 'residential-event-base-add-ons', relatedFiles: withFiles(files.residentialEvents, files.payments, files.map, files.detail), steps: residentialEventSteps }),

  flow({ category: 'Admin', name: 'Dashboard, Residential Listings, Neighborhood Sales, Users, Support Queue, Reports, Billing, Transactions, Listing Detail, Approval Actions, Search, Filters, Status Changes', slug: 'admin-core-management', relatedFiles: withFiles(files.admin, files.payments, files.support), steps: adminSteps }),
  flow({ category: 'Admin', name: 'Assisted Listings and QR Codes Review-Only Flow', slug: 'admin-assisted-qr-review-only', relatedFiles: ['components/admin/assisted/AdminAssistedListingsTab', 'components/admin/assisted/AdminAssistedListingHistory', 'components/admin/assisted/AdminQRViewModal', 'components/admin/assisted/AssistedListingQRPanel', 'pages/AssistedListingApproval'], steps: assistedReviewOnlySteps }),

  flow({ category: 'Approval and Freeze', name: 'Approve Flow', slug: 'qa-approve-flow', relatedFiles: files.qa, steps: qaApprovalSteps }),
  flow({ category: 'Approval and Freeze', name: 'Freeze Flow and Needs Retest Flow', slug: 'qa-freeze-needs-retest-flow', relatedFiles: files.qa, steps: qaFreezeSteps }),
];

export const QA_CATEGORIES = [...new Set(QA_FLOWS.map(flow => flow.category))];