export const STARTER_RESOURCE_MODULES = [
  {
    resource_key: "residential_introduction",
    version_number: 1,
    title: "Introduction",
    section: "Residential Listings",
    category: "Basics",
    lesson_type: "article",
    estimated_minutes: 2,
    display_order: 1,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Residential Listings are the core Yardit experience for individual yard sales, neighborhood sales, and local event-style listings. Staff should understand how listings move from setup to visibility on the public map.",
    examples: "When a seller asks what Yardit does, explain that Yardit helps shoppers discover nearby sales on a map while giving sellers tools to publish accurate sale details.",
    behind_the_scenes: "Residential listing records are stored as Listing records. Different listingType and tier values control how they appear across the app.",
    faq: [{ question: "Who should use this training?", answer: "Admins, support staff, trainers, moderators, and ambassadors who help users understand residential listing flows." }]
  },
  {
    resource_key: "residential_creating_a_listing",
    version_number: 1,
    title: "Creating a Listing",
    section: "Residential Listings",
    category: "Listing Setup",
    lesson_type: "guide",
    estimated_minutes: 3,
    display_order: 2,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "A seller starts by choosing the type of residential listing, adding title/details, confirming location, choosing dates and open hours, then publishing or paying depending on the tier.",
    examples: "If a user says they cannot post a sale, first check whether they are logged in and whether their primary address is verified.",
    behind_the_scenes: "The Create Listing flow gates posting behind profile and address checks before saving the listing data.",
    faq: [{ question: "Can free listings publish immediately?", answer: "Yes. Free residential listings are intended to publish immediately after required details are complete." }]
  },
  {
    resource_key: "residential_listing_information",
    version_number: 1,
    title: "Listing Information",
    section: "Residential Listings",
    category: "Listing Setup",
    lesson_type: "article",
    estimated_minutes: 3,
    display_order: 3,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Listing title, description, categories, photos, and sale details help shoppers decide whether to visit. Descriptions should be clear and accurate.",
    examples: "Good: 'Multi-family yard sale with kids clothes, tools, books, and kitchen items.' Avoid vague titles like 'Stuff for sale'.",
    behind_the_scenes: "Residential yard sale descriptions currently have a shorter limit than neighborhood and event descriptions to keep cards readable.",
    faq: [{ question: "Why are descriptions limited?", answer: "Limits keep listings easy to scan and reduce overly long content on mobile." }]
  },
  {
    resource_key: "residential_address_confirmation",
    version_number: 1,
    title: "Address Confirmation",
    section: "Residential Listings",
    category: "Trust & Location",
    lesson_type: "guide",
    estimated_minutes: 3,
    display_order: 4,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Address confirmation ensures the user has a verified primary address before posting a residential sale. This protects map quality and reduces misleading listings.",
    examples: "If a seller is blocked from posting, ask them to open My Profile and complete primary address verification.",
    behind_the_scenes: "The app checks verified address fields on the user profile before allowing listing creation.",
    faq: [{ question: "Does the public always see the full address?", answer: "The listing display depends on listing details and map behavior, but the system needs a verified location to place it correctly." }]
  },
  {
    resource_key: "residential_scheduling_rules",
    version_number: 1,
    title: "Scheduling Rules",
    section: "Residential Listings",
    category: "Timing",
    lesson_type: "article",
    estimated_minutes: 2,
    display_order: 5,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Scheduling controls which dates a listing is active and what hours shoppers should visit. Staff should distinguish selected sale dates from daily open and close times.",
    examples: "A sale can run Saturday and Sunday from 8:00 AM to 2:00 PM. Those dates are active dates; those hours are open times.",
    behind_the_scenes: "The system stores date ranges and open/close times separately so visibility and shopper information can be calculated reliably.",
    faq: [{ question: "Can listings span multiple days?", answer: "Yes, depending on listing type and tier rules." }]
  },
  {
    resource_key: "residential_open_vs_active_time",
    version_number: 1,
    title: "Open Time vs Active Time",
    section: "Residential Listings",
    category: "Timing",
    lesson_type: "article",
    estimated_minutes: 2,
    display_order: 6,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Open time is when the seller says shoppers should visit. Active time is when the system treats the listing as visible or active based on dates, tier, status, and visibility rules.",
    examples: "A listing may be visible as Coming Soon before the sale opens. That does not mean shoppers should arrive early.",
    behind_the_scenes: "Visibility can include active sale periods and Coming Soon periods. Pin styling may change depending on the current state.",
    faq: [{ question: "Why isn't my listing green yet?", answer: "It may be visible but not currently open. Check the sale date, open time, status, and visibility rules." }]
  },
  {
    resource_key: "residential_free_vs_paid_listings",
    version_number: 1,
    title: "Free vs Paid Listings",
    section: "Residential Listings",
    category: "Tiers",
    lesson_type: "article",
    estimated_minutes: 2,
    display_order: 7,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Free listings provide basic map presence. Paid tiers can add stronger visibility, more features, and expanded promotional benefits depending on the selected tier.",
    examples: "If a seller wants more visibility, explain the available paid tier benefits rather than promising results.",
    behind_the_scenes: "Tier values influence photo limits, date options, visibility behavior, payments, and upgrade flows.",
    faq: [{ question: "Do paid listings guarantee more shoppers?", answer: "No. They improve visibility tools, but staff should not guarantee turnout." }]
  },
  {
    resource_key: "residential_visibility_rules",
    version_number: 1,
    title: "Visibility Rules",
    section: "Residential Listings",
    category: "Visibility",
    lesson_type: "guide",
    estimated_minutes: 3,
    display_order: 8,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "A listing appears based on status, dates, tier, map filters, location, and Coming Soon logic. Support should check each of these before assuming something is broken.",
    examples: "Search phrase: 'Why isn't my listing visible?' Check status, sale date, visibility start date, map zoom, category filters, and whether the user is looking in the correct area.",
    behind_the_scenes: "Visibility is computed from listing fields and map filtering logic rather than a single public/private flag.",
    faq: [{ question: "Why can't I see a listing on the map?", answer: "It may be filtered out, outside the map area, not active yet, hidden, expired, or not visible at the current zoom level." }]
  },
  {
    resource_key: "residential_common_problems",
    version_number: 1,
    title: "Common Problems",
    section: "Residential Listings",
    category: "Support",
    lesson_type: "faq",
    estimated_minutes: 3,
    display_order: 9,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Common residential issues include missing address verification, incorrect sale dates, payment not completed, map filters hiding listings, and expired listings.",
    examples: "When troubleshooting, ask: What listing? What date? What location? What device? What screen are they on?",
    behind_the_scenes: "Many issues are state or timing related. Check the listing record before escalating.",
    faq: [{ question: "What should support check first?", answer: "Confirm the user account, listing status, selected dates, address, and payment state if applicable." }]
  },
  {
    resource_key: "neighborhood_sales_introduction",
    version_number: 1,
    title: "Neighborhood Sales Overview",
    section: "Neighborhood Sales",
    category: "Basics",
    lesson_type: "article",
    estimated_minutes: 3,
    display_order: 1,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Neighborhood Sales group multiple nearby homes into a shared sale experience. Organizers create the event and participants can join or be managed depending on the flow.",
    examples: "Explain to organizers that the neighborhood sale is the umbrella event, while each participating home can have its own sale details.",
    behind_the_scenes: "Neighborhood sales use Listing records plus event state, participant relationships, invite codes, and join statuses.",
    faq: [{ question: "Is a neighborhood sale the same as a yard sale?", answer: "No. It is a group sale structure that may include multiple individual homes." }]
  },
  {
    resource_key: "neighborhood_participants",
    version_number: 1,
    title: "Participants and Home Count",
    section: "Neighborhood Sales",
    category: "Participants",
    lesson_type: "guide",
    estimated_minutes: 3,
    display_order: 2,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Participants are the individual homes connected to a neighborhood sale. Home count and approval status affect how the event is presented.",
    examples: "If an organizer says homes are missing, check whether participants are approved, active, and linked to the correct neighborhood sale.",
    behind_the_scenes: "Participant listings can be standalone or connected through neighborhood sale fields and join statuses.",
    faq: [{ question: "Why is home count lower than expected?", answer: "Some homes may be pending, denied, expired, hidden, or not properly linked." }]
  },
  {
    resource_key: "neighborhood_common_support_questions",
    version_number: 1,
    title: "Common Neighborhood Sale Questions",
    section: "Neighborhood Sales",
    category: "Support",
    lesson_type: "faq",
    estimated_minutes: 3,
    display_order: 3,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Common questions include how to join, why a participant is pending, how co-hosting works, and what happens if required deadlines are missed.",
    examples: "If someone cannot join, check invite code, sale status, location, deadlines, and whether the event is still accepting participants.",
    behind_the_scenes: "Neighborhood sale flows include deadline jobs, co-host invite handling, payment status, and event state changes.",
    faq: [{ question: "Can support approve participants?", answer: "Follow current admin policy and role permissions before changing participant state." }]
  },
  {
    resource_key: "support_triage_basics",
    version_number: 1,
    title: "Support Triage Basics",
    section: "Customer Support",
    category: "Support",
    lesson_type: "guide",
    estimated_minutes: 3,
    display_order: 1,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Start every support issue by identifying the user, listing, page, device, and expected behavior. Then compare that against actual status and known rules.",
    examples: "A strong first response: 'I can help. Which listing are you asking about, and what are you expecting to see?'",
    behind_the_scenes: "Good triage prevents unnecessary escalations and helps developers reproduce real issues faster.",
    faq: [{ question: "When should support escalate?", answer: "Escalate when data looks correct but behavior is still wrong, payments are involved, or user safety/trust is at risk." }]
  },
  {
    resource_key: "support_visibility_questions",
    version_number: 1,
    title: "Answering Visibility Questions",
    section: "Customer Support",
    category: "Visibility",
    lesson_type: "guide",
    estimated_minutes: 3,
    display_order: 2,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Visibility questions are usually about timing, filters, map location, tier rules, or status. Staff should walk through each factor calmly and avoid saying a listing is broken before checking data.",
    examples: "Search phrase: 'Why isn't my listing visible?' Answer by checking listing status, dates, filters, zoom, location, and visibility windows.",
    behind_the_scenes: "Map visibility is calculated from multiple fields and client-side filters, not just whether the listing exists.",
    faq: [{ question: "What is the fastest visibility checklist?", answer: "Status, date/time, map location, filters, zoom level, tier, and payment/activation state." }]
  },
  {
    resource_key: "support_safe_language",
    version_number: 1,
    title: "Safe Support Language",
    section: "Customer Support",
    category: "Communication",
    lesson_type: "article",
    estimated_minutes: 2,
    display_order: 3,
    is_active: true,
    role_visibility: ["admin", "developer"],
    content: "Use clear, calm, non-technical language. Do not promise refunds, turnout, placement, compensation, or timelines unless policy explicitly allows it.",
    examples: "Good: 'I’ll check the listing details and help identify what may be affecting visibility.' Avoid: 'This will definitely bring more shoppers.'",
    behind_the_scenes: "Consistent language reduces risk and keeps support aligned with product behavior.",
    faq: [{ question: "Can staff promise results from paid tiers?", answer: "No. Staff can describe features and visibility tools, but should not guarantee results." }]
  }
];