import React, { useState } from "react";
import { ArrowLeft, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const faqItems = [
  {
    question: "What Is a Neighborhood Sale?",
    answer: "A Neighborhood Sale is a shared event that allows multiple nearby homes to participate together under one Yardit event. Instead of shoppers finding individual yard sales one at a time, they discover an entire neighborhood of participating homes in one location. Each participating home maintains its own listing while benefiting from increased visibility and shopper traffic generated by the larger event.",
  },
  {
    question: "Who Is a Neighborhood Sale For?",
    answer: "Neighborhood Sales work best for: HOA community sales, gated communities, neighborhood-wide yard sale weekends, cul-de-sacs and residential streets, apartment and condominium communities, mobile home communities, senior living communities, church and school fundraising events, and groups of friends or family hosting sales in the same area. If multiple homes are planning sales around the same time, a Neighborhood Sale can help turn several individual sales into one larger destination.",
  },
  {
    question: "How Many Homes Are Required?",
    answer: "A Neighborhood Sale requires a minimum of 5 approved participating homes to activate. All participating homes must be within 500 feet of the selected map location or chosen event address. The organizer's participating home counts toward this total if the organizer chooses to participate. A Neighborhood Sale may have up to 25 participating homes.",
  },
  {
    question: "What Does It Cost?",
    answer: "Only the organizer pays. Participants join free. Organizer pricing: $19.99 base Neighborhood Sale fee plus $2 per approved participating home, with a maximum charge of $50. Examples: 5 homes = $29.99, 10 homes = $39.99, 20 homes = $59.99. Pricing is capped at $50, so the organizer will never pay more than the maximum event fee.",
  },
  {
    question: "When Am I Charged?",
    answer: "The organizer is charged only if the Neighborhood Sale qualifies and moves forward. Participants are never charged.",
  },
  {
    question: "What Happens If I Don't Reach 5 Homes?",
    answer: "Neighborhood Sales must have at least 5 approved participating homes before activation. 48 hours before the event, if fewer than 5 approved homes exist, Yardit sends a reminder notification. 24 hours before the event, if the event still has fewer than 5 approved homes, the Neighborhood Sale is automatically downgraded. Participants are notified and provided options to continue with their own listings.",
  },
  {
    question: "What Happens If Someone Leaves?",
    answer: "If a participant leaves, is removed, deletes their listing, or cancels their listing, the participant is removed from the Neighborhood Sale and participant counts are updated automatically. If the event falls below minimum requirements before activation, the organizer will be notified.",
  },
  {
    question: "Can I Invite People?",
    answer: "Yes. Organizers can invite users directly through Yardit, share their Neighborhood Sale link, encourage neighbors to request participation, and approve or deny requests.",
  },
  {
    question: "Can People Request To Join?",
    answer: "Yes. Users may request to join a Neighborhood Sale if their sale overlaps the Neighborhood Sale dates, their address falls within the event radius, and the organizer approves the request.",
  },
  {
    question: "What If Someone Already Has a Listing?",
    answer: "Existing listings may join a Neighborhood Sale if they qualify. Neighborhood participation uses the overlapping dates between the listing and the event. For example, if a listing runs Wednesday through Monday and the Neighborhood Sale runs Saturday through Sunday, the listing participates in the Neighborhood Sale on Saturday and Sunday only.",
  },
  {
    question: "What Is a Co-Host?",
    answer: "A Co-Host is a user invited by the organizer to help manage the event. Co-Hosts may view participants, manage participation requests, and help coordinate the event. Co-Hosts do not own the event and cannot delete it. The co-host's home must be within 500 feet of the event center to be approved as a co-host.",
  },
  {
    question: "What Am I Responsible For As Organizer?",
    answer: "The most successful organizers personally invite neighbors, share their Yardit event link, approve participation requests, help the event reach activation requirements, and keep participants informed. Yardit helps organize the event, but organizers are responsible for building participation.",
  },
  {
    question: "Why Do Neighborhood Sales Work?",
    answer: "Neighborhood Sales create stronger destinations for shoppers. Benefits include more shopper traffic, longer shopper visits, better visibility, increased exposure, and greater participation. More homes equals more traffic.",
  },
  {
    question: "Where Can I Get Additional Help?",
    answer: "If you still have questions, contact Yardit Support or visit the Help Center.",
  },
];

export default function NeighborhoodIntroFAQ({ onBack }) {
  const [expandedFaq, setExpandedFaq] = useState(null);

  const toggleFaq = (index) => {
    setExpandedFaq((current) => {
      const next = current === index ? null : index;
      if (next !== null) {
        setTimeout(() => {
          document.querySelector(`[data-neighborhood-faq-card="${index}"]`)?.scrollIntoView({ behavior: "smooth", block: "start" });
        }, 50);
      }
      return next;
    });
  };

  return (
    <>
      <div className="border-b border-[#2C4F4E]/10 bg-white/90 px-4 py-3 sm:px-5">
        <button
          type="button"
          onClick={onBack}
          className="mb-2 inline-flex items-center gap-1.5 text-sm font-bold text-[#006168] hover:underline"
        >
          <ArrowLeft className="h-4 w-4" /> Back to intro
        </button>
        <DialogHeader>
          <DialogTitle className="text-lg font-black text-[#2C4F4E]">Neighborhood Sale FAQ</DialogTitle>
          <p className="text-sm text-slate-600">Quick details about creating and managing your event.</p>
        </DialogHeader>
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto px-4 py-4 sm:px-5">
        <div className="space-y-3">
          {faqItems.map((item, index) => {
            const expanded = expandedFaq === index;
            return (
              <section key={item.question} data-neighborhood-faq-card={index} className="overflow-hidden rounded-2xl border border-[#5DADA5]/20 bg-white shadow-sm">
                <button
                  type="button"
                  onClick={() => toggleFaq(index)}
                  className="flex w-full items-center justify-between gap-3 p-4 text-left touch-manipulation"
                >
                  <h3 className="text-sm font-bold text-[#2C4F4E]">{item.question}</h3>
                  <ChevronDown className={`h-4 w-4 shrink-0 text-[#5DADA5] transition-transform ${expanded ? "rotate-180" : ""}`} />
                </button>
                {expanded && (
                  <p className="border-t border-[#5DADA5]/15 bg-[#F9F4EA]/70 px-4 pb-4 pt-3 text-sm leading-relaxed text-slate-700">{item.answer}</p>
                )}
              </section>
            );
          })}
        </div>
      </div>

      <DialogFooter className="shrink-0 border-t border-[#2C4F4E]/10 bg-white/85 px-4 py-3 sm:px-5">
        <Button type="button" onClick={onBack} className="w-full rounded-xl bg-[#006168] font-bold text-white hover:bg-[#004d52]">
          Return to Intro
        </Button>
      </DialogFooter>
    </>
  );
}